'use client'

import localFont from "next/font/local";
import "../styles/globals.scss";
import { Providers } from "./providers";
import Link from "next/link";
import AdminLayout from "./auth/layout";
import { usePathname } from "next/navigation";
import { useState } from "react";
import burgerMenu from '@/styles/img/Navigation/Icon.svg'
import Image from "next/image";

const fonts = localFont({
  src: [
    {
      path: '../styles/fonts/montserrat/Montserrat-Light.ttf',
      style: 'inherit',
      weight: '300'
    },
    {
      path: '../styles/fonts/montserrat/Montserrat-Medium.ttf',
      style: 'inherit',
      weight: '500'
    },
    {
      path: '../styles/fonts/montserrat/Montserrat-Regular.ttf',
      style: 'inherit',
      weight: '400'
    },
    {
      path: '../styles/fonts/montserrat/Montserrat-SemiBold.ttf',
      style: 'inherit',
      weight: '600'
    },
    {
      path: '../styles/fonts/montserrat/Montserrat-Bold.ttf',
      style: 'inherit',
      weight: '700'
    },
    {
      path: '../styles/fonts/montserrat/Montserrat-Black.ttf',
      style: 'inherit',
      weight: '900'
    },
  ],
})

const menuItems = [
  { href: "/nomenclatures", label: "Номенклатуры" },
  { href: "/files", label: "Файлы" },
  { href: "/playlists", label: "Плейлисты" },
  { href: "/orders", label: "Заказы" },
  { href: "/tasks", label: "Задачи" },
];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const pathname = usePathname();

  const isLoginPage = pathname === "/auth";

  const [openSideBar, setOpenSideBar] = useState<boolean>(false);
  const [isAnimating, setIsAnimating] = useState<boolean>(false);

  const toggleSidebar = () => {
    if (isAnimating) return; // Блокируем повторное нажатие во время анимации
    setIsAnimating(true);
    setOpenSideBar((prev) => !prev);

    // Устанавливаем таймер завершения анимации (300ms как в SCSS)
    setTimeout(() => setIsAnimating(false), 300);
  };




  return (
    <html lang="en">
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <meta name="description" content="Generated by create next app" />
      <body className={`${fonts.className} antialiased`}>
        <Providers>
          {isLoginPage ? (
            <AdminLayout>{children}</AdminLayout>
          ) : (
            <div className="layout">
              <aside
                className={`sidebar ${openSideBar ? "open" : "closed"
                  } ${isAnimating ? "animating" : ""}`}
              >
                <div className="sidebar__title">
                  <Link href={"/home"}>RMC ADMIN</Link>
                </div>
                <div className="sidebar__menu">
                  {menuItems.map((item) => (
                    <div
                      key={item.href}
                      className={`sidebar__menu-item ${pathname.startsWith(item.href) ? "active" : ""
                        }`}
                    >
                      <Link href={item.href}>{item.label}</Link>
                    </div>
                  ))}
                </div>
              </aside>
              <div className="main">
                <header
                  className={`header ${!openSideBar ? "full-width" : ""}`}
                >
                  <div
                    className="header__toggle"
                    onClick={toggleSidebar}
                  >
                    <Image src={burgerMenu} alt="burgerMenu" width={24} height={24} />
                  </div>
                </header>
                <main className="content">{children}</main>
              </div>
            </div>
          )}
        </Providers>
      </body>
    </html>
  );
}
