volumes:
  pg_data:
  static:
  celery:
  s3:

services:
  db:
    image: postgres:16.2
    container_name: db
    env_file: .env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 5
#    restart: unless-stopped
    volumes:
      - pg_data:/var/lib/postgresql/data

  files:
    image: minio/minio
    container_name: files
    env_file: .env
    expose:
      - 9000
      - 9001
    ports:
      - 9000:9000
      - 9001:9001
    command: server /data --console-address ":9001"
    volumes:
      - s3:/data

  backend:
    build: ./backend
    container_name: backend
    env_file: .env
    ports:
      - 8000:8000
    depends_on:
      files:
        condition: service_started
      db:
        condition: service_healthy

  frontend:
    env_file: .env
    environment:
      - NEXT_PUBLIC_API_URL=${APP_SERVER_URL}
    container_name: frontend
    build: ./frontend
    ports:
      - 3000:3000
    depends_on:
      - backend
    volumes:
      - static:/frontend_static

  gateway:
    build: ./nginx
    container_name: gateway
#    restart: always
    env_file: .env
    volumes:
      - static:/staticfiles
    ports:
      - 80:80
    depends_on:
      - backend
      - frontend

#  rabbit:
#    image: rabbitmq:3.13-management
#    container_name: rabbit
#    env_file: .env
##    restart: always
#    ports:
#      - 5672:5672
#      - 15672:15672
#
#  celery:
#    build: ./backend
#    container_name: celery
#    env_file: .env
#    volumes:
#      - celery:/app
#    depends_on:
#      - backend
#      - rabbit
#
#  dashboard:
#    build: ./backend
#    container_name: dashboard
#    env_file: .env
#    command: flower -A backend --port=5555 --broker=${CELERY_BROKER}
#    ports:
#      - 5555:5555
#    depends_on:
#      - backend
#      - rabbit
#      - celery