services:
  opensearch:
    image: opensearchproject/opensearch:2.13.0
    environment:
      - discovery.type=single-node
      - DISABLE_SECURITY_PLUGIN=true
      - OPENSEARCH_JAVA_OPTS=-Xms2g -Xmx2g  # половина от mem_limit
    ports:
      - "9200:9200"
    volumes:
      - /base/rmc_rest_api_opensearch-data:/usr/share/opensearch/data
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9200" ]
      interval: 10s
      timeout: 5s
      retries: 10
    restart: unless-stopped
    mem_limit: 4G
    mem_reservation: 2G
    cpus: '2'
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse
    env_file: .env
    ports:
      - 8123:8123
      - 8888:9000
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8123/ping || exit 1
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    volumes:
      - /file/clickhouse_data/_data:/var/lib/clickhouse
    ulimits:
      nofile: 262144
    mem_limit: 16G
    mem_reservation: 8G
    cpus: '8'

  db:
    image: postgres:18.3
    container_name: db
    env_file: .env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_NAME=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_PASSWORD=${POSTGRES_PASS}
      - PGDATA=/var/lib/postgresql/18/docker
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}']
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    ports:
      - 5432:5432
    shm_size: '2g'
    volumes:
      - ./scripts/postgres:/docker-entrypoint-initdb.d
      - /base:/var/lib/postgresql
      #      - ./configs/postgres/postgres_optimized.conf:/var/lib/postgresql/18/docker/postgresql.conf
      #      - /var/log/postgresql_nvme:/var/log/postgresql:rw
      - ./db_dumps:/db_dumps
    deploy:
      resources:
        limits:
          memory: 16G
          cpus: '8'
        reservations:
          memory: 12G
          cpus: '4'
    sysctls:
      - kernel.shmall=17179869184
      - kernel.shmmax=68719476736
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
      nproc:
        soft: 65536
        hard: 65536
    mem_limit: 16G
    mem_reservation: 12G
    cpus: '8'
    command: >
      postgres
      -c shared_buffers=4GB
      -c effective_cache_size=12GB
      -c maintenance_work_mem=2GB
      -c checkpoint_completion_target=0.9
      -c wal_buffers=64MB
      -c default_statistics_target=100
      -c random_page_cost=1.1
      -c effective_io_concurrency=300
      -c work_mem=64MB
      -c max_connections=200
      -c fsync=on
      -c synchronous_commit=off
      -c full_page_writes=off
      -c bgwriter_delay=200ms
      -c bgwriter_lru_maxpages=1000
      -c max_wal_size=16GB
      -c min_wal_size=4GB
      -c checkpoint_timeout=15min

  files:
    image: minio/minio:RELEASE.2025-04-22T22-12-26Z
    container_name: files
    env_file: .env
    command: server /data --console-address ":9001"
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:9000/minio/health/live']
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - /file/s3:/data
    ports:
      - 9000:9000
      - 9001:9001
    mem_limit: 4G
    mem_reservation: 2G
    cpus: '2'

  backend:
    build: ./backend
    container_name: backend
    env_file: .env
    volumes:
      - ./scripts/backend:/app/scripts
      - ./backend/addresses/migrations:/app/addresses/migrations
      - ./backend/brands/migrations:/app/brands/migrations
      - ./backend/users/migrations:/app/users/migrations
      - ./backend/counterparties/migrations:/app/counterparties/migrations
      - ./backend/files/migrations:/app/files/migrations
      - ./backend/nomenclatures/migrations:/app/nomenclatures/migrations
      - ./backend/orders/migrations:/app/orders/migrations
      - ./backend/ch_statistic/migrations:/app/ch_statistic/migrations
      - ./backend/tasks/migrations:/app/tasks/migrations
      - ./backend/promotions/migrations:/app/promotions/migrations
    healthcheck:
      test: curl --fail ${BACKEND_HC} || exit 1
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - 8000:8000
    command: gunicorn --bind 0:8000 --workers 18 --threads 8 --timeout 90 rmc_rest_api.wsgi
    restart: unless-stopped
    depends_on:
      files:
        condition: service_healthy
      db:
        condition: service_healthy
      clickhouse:
        condition: service_healthy
      rabbit:
        condition: service_healthy
      opensearch:
        condition: service_healthy
    #environment:
    #- RM_USER=${RM_USER}
    #- RM_PASS=${RM_PASS}
    #- URL_1C=${URL_1C}
    #- RM_LK_PASS=${RM_LK_PASS}
    #- RM_LK_EMAIL=${RM_LK_EMAIL}
    mem_limit: 24G
    mem_reservation: 16G
    cpus: '16'

  worker:
    build: ./backend
    env_file: .env
    volumes:
      - ./scripts/backend:/app/scripts
    restart: unless-stopped
    depends_on:
      backend:
        condition: service_healthy
    command: >
      celery -A rmc_rest_api worker
      --loglevel=INFO
      --concurrency=2
      --max-tasks-per-child=1000
      --max-memory-per-child=512000
      --prefetch-multiplier=1
    deploy:
      replicas: 8
    mem_limit: 2G
    mem_reservation: 1.5G
    cpus: '2'

  beat:
    build: ./backend
    container_name: celery_beat
    env_file: .env
    volumes:
      - ./scripts/backend:/app/scripts
    restart: unless-stopped
    depends_on:
      backend:
        condition: service_healthy
    command: >
      celery -A rmc_rest_api beat
      --loglevel=INFO
      --schedule=/tmp/celerybeat-schedule
    mem_limit: 1G
    mem_reservation: 512M
    cpus: '1'

  gateway:
    build: ./nginx
    container_name: gateway
    env_file: .env
    volumes:
      - /file/static:/staticfiles
    ports:
      - 80:80
    restart: unless-stopped
    depends_on:
      backend:
        condition: service_healthy
    mem_limit: 4G
    mem_reservation: 2G
    cpus: '4'

  rabbit:
    image: rabbitmq:4.2.2-management
    container_name: rabbit
    hostname: rabbit
    env_file: .env # Загружает все переменные из .env
    environment:
      # Явно указываем переменные для RabbitMQ (берутся из .env)
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASS}
      - RABBITMQ_DEFAULT_VHOST=/
      # Опционально, для ясности:
      - RABBITMQ_NODENAME=rabbit@rabbit
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=+A 128 +P 1048576
      - RABBITMQ_DEPRECATED_FEATURES_PERMIT_MANAGEMENT_METRICS_COLLECTION=true
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 5s
      timeout: 10s
      retries: 10
    restart: unless-stopped
    volumes:
      - /base/rabbitmq:/var/lib/rabbitmq
    #      - /opt/rabbitmq/logs:/var/log/rabbitmq
    #     - ./configs/rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    #     - ./configs/rabbitmq/definitions.json:/etc/rabbitmq/definitions.json
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - 5672:5672
      - 15672:15672
    mem_limit: 4G
    mem_reservation: 2G
    cpus: '2'

  dashboard:
    image: mher/flower
    container_name: dashboard
    env_file: .env
    command: >
      celery flower
      --max-tasks=10000
      --persistent=False
    volumes:
      - /file/celery:/app
    ports:
      - 5555:5555
    restart: unless-stopped
    depends_on:
      gateway:
        condition: service_started
    mem_limit: 512M
    mem_reservation: 256M
    cpus: '0.5'

  redis:
    image: redis:8.4.0-alpine
    container_name: redis
    hostname: redis
    restart: unless-stopped
    command: >
      redis-server
      --maxmemory 6GB
      --maxmemory-policy allkeys-lru
      --save ""
      --appendonly no
      --protected-mode no
      --maxclients 5000
      --tcp-backlog 512
      --timeout 300
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 5s
      retries: 3
    mem_limit: 6G
    mem_reservation: 4G
    cpus: '2'
    sysctls:
      - net.core.somaxconn=512

  pgadmin:
    image: dpage/pgadmin4:9.9.0
    env_file: .env
    environment:
      PGADMIN_DEFAULT_EMAIL: ${DJANGO_SUPERUSER_NAME}
      PGADMIN_DEFAULT_PASSWORD: ${DJANGO_SUPERUSER_PASS}
      PGADMIN_LISTEN_PORT: 15432
    ports:
      - 15432:15432
    volumes:
      - /file/pgadmin:/var/lib/pgadmin
    depends_on:
      - db
    mem_limit: 2G
    mem_reservation: 1G
    cpus: '2'
volumes:
  opensearch-data:

#volumes:
#brand_logs:
#driver: local
#driver_opts:
#type: cifs
#o: username=${RM_USER},password=${RM_PASS},vers=3.0
#device: '//192.168.0.2/rm/brands_logs'
