services:
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse
    env_file: .env
    ports:
      - 8123:8123
      - 8888:9000
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8123/ping || exit 1
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    volumes:
      - /file/clickhouse_data/_data:/var/lib/clickhouse
    deploy:
      resources:
        limits:
          memory: 16G
          cpus: '8'
        reservations:
          memory: 8G
          cpus: '4'
    ulimits:
      nofile: 262144

  db:
    image: postgres:16.9
    container_name: db
    env_file: .env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_NAME=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_PASSWORD=${POSTGRES_PASS}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - ./scripts/postgres:/docker-entrypoint-initdb.d
      - /file/pg_data/_data:/var/lib/postgresql/data
      - ./db_dumps:/db_dumps
    deploy:
      resources:
        limits:
          memory: 64G
          cpus: '16'
        reservations:
          memory: 48G
          cpus: '8'

  files:
    image: minio/minio
    container_name: files
    env_file: .env
    command: server /data --console-address ":9001"
    restart: unless-stopped
    healthcheck:
      test: curl -I ${MINIO_EXTERNAL_ENDPOINT}/minio/health/live
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - /file/s3:/data
    ports:
      - 9000:9000
      - 9001:9001
    deploy:
      resources:
        limits:
          memory: 4G
          cpus: '2'
        reservations:
          memory: 2G
          cpus: '1'

  backend:
    build: ./backend
    container_name: backend
    env_file: .env
    volumes:
      - ./scripts/backend:/app/scripts
    healthcheck:
      test: curl --fail ${BACKEND_HC} || exit 1
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - 8000:8000
    command: gunicorn --bind 0:8000 --workers 58 --timeout 90 rmc_rest_api.wsgi
    restart: unless-stopped
    depends_on:
      files:
        condition: service_healthy
      db:
        condition: service_healthy
      clickhouse:
        condition: service_healthy
      rabbit:
        condition: service_healthy
    environment:
      - RM_USER=${RM_USER}
      - RM_PASS=${RM_PASS}
      - URL_1C=${URL_1C}
      - RM_LK_PASS=${RM_LK_PASS}
      - RM_LK_EMAIL=${RM_LK_EMAIL}
    deploy:
      resources:
        limits:
          memory: 24G
          cpus: '16'
        reservations:
          memory: 16G
          cpus: '8'

  worker:
    build: ./backend
    env_file: .env
    volumes:
      - ./scripts/backend:/app/scripts
    restart: unless-stopped
    depends_on:
      backend:
        condition: service_healthy
    command: celery -A rmc_rest_api worker
    deploy:
      replicas: 24
      resources:
        limits:
          memory: 4G
          cpus: '4'
        reservations:
          memory: 2G
          cpus: '2'

  beat:
    build: ./backend
    container_name: celery_beat
    env_file: .env
    volumes:
      - ./scripts/backend:/app/scripts
    restart: unless-stopped
    depends_on:
      backend:
        condition: service_healthy
    command: celery -A rmc_rest_api beat
    deploy:
      resources:
        limits:
          memory: 4G
          cpus: '8'
        reservations:
          memory: 2G
          cpus: '4'

  frontend:
    env_file: .env
    container_name: frontend
    build: ./frontend
    ports:
      - 3000:3000
    restart: unless-stopped
    depends_on:
      backend:
        condition: service_healthy
    volumes:
      - /file/static:/frontend_static
    deploy:
      resources:
        limits:
          memory: 4G
          cpus: '4'
        reservations:
          memory: 2G
          cpus: '2'

  gateway:
    build: ./nginx
    container_name: gateway
    env_file: .env
    volumes:
      - /file/static:/staticfiles
    ports:
      - 80:80
    restart: unless-stopped
    depends_on:
      backend:
        condition: service_healthy
      frontend:
        condition: service_started
    deploy:
      resources:
        limits:
          memory: 4G
          cpus: '4'
        reservations:
          memory: 2G
          cpus: '2'

  rabbit:
    image: rabbitmq:4.1.3-management
    container_name: rabbit
    hostname: rabbit
    env_file: .env
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 5s
      timeout: 10s
      retries: 10
    restart: unless-stopped
    volumes:
      - /file/rabbitdata:/var/lib/rabbitmq
      - ./configs/rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    ports:
      - 5672:5672
      - 15672:15672
    deploy:
      resources:
        limits:
          memory: 4G
          cpus: '4'
        reservations:
          memory: 2G
          cpus: '2'

  dashboard:
    image: mher/flower
    container_name: dashboard
    env_file: .env
    command: celery flower
    volumes:
      - /file/celery:/app
    ports:
      - 5555:5555
    restart: unless-stopped
    depends_on:
      gateway:
        condition: service_started
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1'
        reservations:
          memory: 512M
          cpus: '0.5'

  redis:
    image: redis:8.2.0-alpine
    container_name: redis
    hostname: redis
    restart: unless-stopped
    command: >
      redis-server
      --maxmemory 4GB
      --maxmemory-policy allkeys-lru
      --save ""
      --appendonly no
      --protected-mode no
    deploy:
      resources:
        limits:
          memory: 8G
          cpus: '8'
        reservations:
          memory: 4G
          cpus: '4'

  pgadmin:
    image: dpage/pgadmin4:9.5
    env_file: .env
    environment:
      PGADMIN_DEFAULT_EMAIL: ${DJANGO_SUPERUSER_NAME}
      PGADMIN_DEFAULT_PASSWORD: ${DJANGO_SUPERUSER_PASS}
      PGADMIN_LISTEN_PORT: 15432
    ports:
      - 15432:15432
    volumes:
      - /file/pgadmin:/var/lib/pgadmin
    depends_on:
      - db
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '2'
        reservations:
          memory: 1G
          cpus: '1'


volumes:
  brand_logs:
    driver: local
    driver_opts:
      type: cifs
      o: username=${RM_USER},password=${RM_PASS},vers=3.0
      device: "//192.168.0.2/rm/brands_logs"