# Generated by Django 5.0.3 on 2024-05-16 07:23

import django.contrib.postgres.fields.hstore
import django.contrib.postgres.fields.ranges
import django.db.models.deletion
import orders.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nomenclatures', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BgOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('broadcast_interval', django.contrib.postgres.fields.ranges.DateTimeRangeField(verbose_name='Интервал работы заказа')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('order_type', models.IntegerField(choices=[(1, 'Фоновая музыка'), (2, 'Фоновые видео'), (3, 'Фоновые картинки'), (4, 'Бегущая строка')], default=1, verbose_name='Тип фона')),
            ],
            options={
                'verbose_name': 'Фоновый заказ',
                'verbose_name_plural': 'Фон',
                'db_table': 'bg_order',
            },
        ),
        migrations.CreateModel(
            name='AdOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('broadcast_interval', django.contrib.postgres.fields.ranges.DateTimeRangeField(verbose_name='Интервал работы заказа')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('broadcast_type', models.PositiveSmallIntegerField(choices=[(0, 'По времени работы точки'), (1, 'Начало работы + смещение по времени'), (2, 'Конец работы - смещение по времени'), (3, 'Конкретные часы'), (4, 'С открытия до фиксированного часа'), (5, 'С фиксированного часа до закрытия'), (6, 'Старт по событию')], default=0, verbose_name='Тип вещания')),
                ('parameters', django.contrib.postgres.fields.hstore.HStoreField(default=orders.models.AdOrder.default_parameters, verbose_name='Параметры заказа')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_file', to='files.file', verbose_name='Файл')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nomenclatures.nomenclaturegroup', verbose_name='Группа номенклатур')),
            ],
            options={
                'verbose_name': 'Рекламный заказ',
                'verbose_name_plural': 'Реклама',
                'db_table': 'ad_order',
            },
        ),
    ]
