# Generated by Django 5.0.3 on 2024-04-26 02:26

import django.contrib.postgres.fields.ranges
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('files', '0001_initial'),
        ('nomenclatures', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('type', models.PositiveSmallIntegerField(choices=[(0, 'Реклама'), (1, 'Фоновая музыка'), (2, 'Фоновые видео'), (3, 'Фоновые картинки'), (4, 'Бегущая строка')], verbose_name='Тип')),
                ('broadcast_interval', django.contrib.postgres.fields.ranges.DateTimeRangeField(verbose_name='Интервал работы заказа')),
                ('broadcast_type', models.PositiveSmallIntegerField(choices=[(0, 'По времени работы точки'), (1, 'Начало работы + смещение по времени'), (2, 'Конец работы - смещение по времени'), (3, 'Конкретные часы'), (4, 'С открытия до фиксированного часа'), (5, 'С фиксированного часа до закрытия'), (6, 'Старт по событию')], default=0, verbose_name='Тип вещания')),
                ('parameters', models.JSONField(default={'active_ad': 'close', 'daily_end_time': '21:00:00', 'daily_start_time': '09:00:00', 'event': 'play if click button', 'timedelta': '01:30:00', 'times_in_hour': 4, 'weight': 50}, verbose_name='Параметры заказа')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nomenclatures.nomenclaturegroup', verbose_name='Группа номенклатур')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='files.playlist', verbose_name='Плейлист')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'db_table': 'order',
            },
        ),
    ]
