# Generated by Django 5.0.3 on 2024-05-16 07:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('files', '0002_initial'),
        ('nomenclatures', '0002_initial'),
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='adorder',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Создатель'),
        ),
        migrations.AddField(
            model_name='adorder',
            name='slides',
            field=models.ManyToManyField(blank=True, related_name='ad_slide', to='files.file', verbose_name='Слайды'),
        ),
        migrations.AddField(
            model_name='bgorder',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nomenclatures.nomenclature', verbose_name='Номенклатура'),
        ),
        migrations.AddField(
            model_name='bgorder',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Создатель'),
        ),
        migrations.AddField(
            model_name='bgorder',
            name='playlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='files.playlist', verbose_name='Плейлист'),
        ),
    ]
