# Generated by Django 6.0.1 on 2026-05-18 16:47

import django.contrib.postgres.fields.ranges
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bgorder',
            name='is_permanent',
            field=models.BooleanField(default=False, help_text='Если включено — заказ не имеет даты окончания и используется как резервный плейлист. Играет когда нет активных заказов с датами.', verbose_name='Бессрочный заказ'),
        ),
        migrations.AlterField(
            model_name='adorder',
            name='broadcast_interval',
            field=django.contrib.postgres.fields.ranges.DateTimeRangeField(blank=True, null=True, verbose_name='Интервал работы заказа'),
        ),
        migrations.AlterField(
            model_name='bgorder',
            name='broadcast_interval',
            field=django.contrib.postgres.fields.ranges.DateTimeRangeField(blank=True, null=True, verbose_name='Интервал работы заказа'),
        ),
    ]
