# Generated by Django 5.2.3 on 2025-06-27 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bgorder',
            name='parameters',
            field=models.JSONField(verbose_name='Параметры заказа'),
        ),
    ]
