# Generated by Django 5.0.3 on 2024-04-17 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_options_alter_order_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='broadcast_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'По времени работы точки'), (1, 'Начало работы + смещение по времени'), (2, 'Конец работы - смещение по времени'), (3, 'Конкретные часы'), (4, 'С открытия до фиксированного часа'), (5, 'С фиксированного часа до закрытия'), (6, 'Старт по событию')], default=0, verbose_name='Тип вещания'),
        ),
        migrations.AddField(
            model_name='order',
            name='parameters',
            field=models.JSONField(default={'active_ad': 'close', 'daily_end_time': '21:00:00', 'daily_start_time': '09:00:00', 'event': 'play if click button', 'timedelta': '01:30:00', 'times_in_hour': 4, 'weight': 50}, verbose_name='Параметры заказа'),
        ),
    ]
