# Generated by Django 6.0.1 on 2026-03-30 10:39

import django.contrib.postgres.indexes
import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdministrativeTerritory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Уникальный идентификатор')),
                ('name', models.CharField(help_text='Название административного округа', max_length=255, verbose_name='Административный округ')),
            ],
            options={
                'verbose_name': 'Административный округ',
                'verbose_name_plural': 'Административные округа',
                'db_table': 'addresses_administrative_territory',
                'ordering': ['city__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Уникальный идентификатор')),
                ('name', models.CharField(help_text='Название населенного пункта', max_length=255, verbose_name='Наименование города')),
                ('has_atd', models.BooleanField(default=False, help_text='Наличие административно-территориального деления', verbose_name='Наличие АТД')),
                ('atd_type', models.CharField(blank=True, help_text='Тип административно-территориального деления', max_length=255, null=True, verbose_name='Тип АТД')),
                ('has_administrative_territory', models.BooleanField(default=False, help_text='Наличие административных округов (например, в Москве)', verbose_name='Наличие административного округа')),
            ],
            options={
                'verbose_name': 'Населённый пункт',
                'verbose_name_plural': 'Населённые пункты',
                'db_table': 'addresses_city',
                'ordering': ['region__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Coordinates',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Уникальный идентификатор')),
                ('latitude', models.CharField(blank=True, help_text='Географическая широта в градусах (от -90 до 90)', max_length=31, null=True, verbose_name='Широта')),
                ('longitude', models.CharField(blank=True, help_text='Географическая долгота в градусах (от -180 до 180)', max_length=31, null=True, verbose_name='Долгота')),
            ],
            options={
                'verbose_name': 'Координаты',
                'verbose_name_plural': 'Координаты',
                'db_table': 'addresses_coordinates',
            },
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Уникальный идентификатор')),
                ('number', models.CharField(help_text='Номер дома (может содержать буквы и дроби)', max_length=31, verbose_name='Номер дома')),
            ],
            options={
                'verbose_name': 'Дом',
                'verbose_name_plural': 'Дома',
                'db_table': 'addresses_house',
                'ordering': ['street__name', 'number'],
            },
        ),
        migrations.CreateModel(
            name='AdministrativeTerritorialUnit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Уникальный идентификатор')),
                ('name', models.CharField(help_text='Название административно-территориальной единицы', max_length=255, verbose_name='Район / округ')),
                ('administrative_territory', models.ForeignKey(blank=True, help_text='Административный округ (если район входит в округ)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='territorial_units', to='addresses.administrativeterritory', verbose_name='Административный округ')),
                ('city', models.ForeignKey(help_text='Город, в котором находится район/округ', on_delete=django.db.models.deletion.PROTECT, related_name='territorial_units', to='addresses.city', verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Административно-территориальная единица',
                'verbose_name_plural': 'Административно-территориальные единицы',
                'db_table': 'addresses_administrative_territorial_unit',
                'ordering': ['city__name', 'name'],
            },
        ),
        migrations.AddField(
            model_name='administrativeterritory',
            name='city',
            field=models.ForeignKey(help_text='Город, в котором находится административный округ', on_delete=django.db.models.deletion.PROTECT, related_name='administrative_territories', to='addresses.city', verbose_name='Город'),
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Автоматически генерируемый UUID идентификатор страны', primary_key=True, serialize=False, verbose_name='Уникальный идентификатор')),
                ('name', models.CharField(db_index=True, help_text='Полное официальное название страны на русском языке', max_length=255, unique=True, verbose_name='Название страны')),
            ],
            options={
                'verbose_name': 'Страна',
                'verbose_name_plural': 'Страны',
                'db_table': 'addresses_country',
                'ordering': ['name'],
                'indexes': [django.contrib.postgres.indexes.BTreeIndex(fields=['name'], name='country_name_btree_idx'), django.contrib.postgres.indexes.GinIndex(fields=['name'], name='country_name_gin_idx', opclasses=['gin_trgm_ops'])],
            },
        ),
        migrations.CreateModel(
            name='FederalDistrict',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Уникальный идентификатор')),
                ('name', models.CharField(help_text='Полное название федерального округа', max_length=255, verbose_name='Название федерального округа')),
                ('abbreviated_name', models.CharField(help_text='Сокращенное название (например, ЦФО, СЗФО, ЮФО)', max_length=50, verbose_name='Сокращенное название')),
                ('country', models.ForeignKey(help_text='Страна, к которой относится федеральный округ', on_delete=django.db.models.deletion.PROTECT, related_name='federal_districts', to='addresses.country', verbose_name='Страна')),
            ],
            options={
                'verbose_name': 'Федеральный округ',
                'verbose_name_plural': 'Федеральные округа',
                'db_table': 'addresses_federal_district',
                'ordering': ['country__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Уникальный идентификатор')),
                ('number', models.CharField(help_text='Номер корпуса или строения', max_length=31, verbose_name='Корпус / строение')),
                ('house', models.ForeignKey(help_text='Дом, к которому относится строение', on_delete=django.db.models.deletion.PROTECT, related_name='buildings', to='addresses.house', verbose_name='Дом')),
            ],
            options={
                'verbose_name': 'Здание / строение',
                'verbose_name_plural': 'Здания / строения',
                'db_table': 'addresses_building',
                'ordering': ['house__street__name', 'house__number', 'number'],
            },
        ),
        migrations.CreateModel(
            name='LocalityType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Уникальный идентификатор')),
                ('name', models.CharField(help_text='Тип населенного пункта (город, деревня, поселок и т.д.)', max_length=255, unique=True, verbose_name='Тип населённого пункта')),
                ('abbreviated_name', models.CharField(blank=True, help_text='Сокращенное обозначение типа (г., д., п. и т.д.)', max_length=50, null=True, verbose_name='Сокращённое наименование')),
                ('show_before_name', models.BooleanField(default=False, help_text="Если отмечено: 'г. Москва', если нет: 'Москва г.'", verbose_name='Отображать тип до наименования')),
                ('has_administrative_territory', models.BooleanField(default=False, help_text='Для городов федерального значения (Москва, Санкт-Петербург)', verbose_name='Имеет административный округ')),
            ],
            options={
                'verbose_name': 'Тип населённого пункта',
                'verbose_name_plural': 'Типы населённых пунктов',
                'db_table': 'addresses_locality_type',
                'ordering': ['name'],
                'indexes': [django.contrib.postgres.indexes.BTreeIndex(fields=['name'], name='locality_type_name_idx'), django.contrib.postgres.indexes.GinIndex(fields=['name'], name='locality_type_name_gin_idx', opclasses=['gin_trgm_ops'])],
            },
        ),
        migrations.AddField(
            model_name='city',
            name='locality_type',
            field=models.ForeignKey(help_text='Тип населенного пункта (город, деревня и т.д.)', on_delete=django.db.models.deletion.PROTECT, related_name='cities', to='addresses.localitytype', verbose_name='Тип населённого пункта'),
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Уникальный идентификатор')),
                ('name', models.CharField(help_text='Название региона без указания типа', max_length=255, verbose_name='Наименование региона')),
                ('abbreviated_name', models.CharField(blank=True, help_text='Сокращенное название региона (если есть)', max_length=255, null=True, verbose_name='Сокращенное наименование')),
                ('federal_district', models.ForeignKey(help_text='Федеральный округ, в который входит регион', on_delete=django.db.models.deletion.PROTECT, related_name='regions', to='addresses.federaldistrict', verbose_name='Федеральный округ')),
            ],
            options={
                'verbose_name': 'Регион',
                'verbose_name_plural': 'Регионы',
                'db_table': 'addresses_region',
                'ordering': ['federal_district__name', 'name'],
            },
        ),
        migrations.AddField(
            model_name='city',
            name='region',
            field=models.ForeignKey(help_text='Регион, к которому относится город', on_delete=django.db.models.deletion.PROTECT, related_name='cities', to='addresses.region', verbose_name='Регион'),
        ),
        migrations.CreateModel(
            name='Street',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Уникальный идентификатор')),
                ('name', models.CharField(help_text='Название улицы без указания типа', max_length=255, verbose_name='Наименование улицы')),
                ('city', models.ForeignKey(help_text='Город, в котором находится улица', on_delete=django.db.models.deletion.PROTECT, related_name='streets', to='addresses.city', verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Улица',
                'verbose_name_plural': 'Улицы',
                'db_table': 'addresses_street',
                'ordering': ['city__name', 'name'],
            },
        ),
        migrations.AddField(
            model_name='house',
            name='street',
            field=models.ForeignKey(help_text='Улица, на которой расположен дом', on_delete=django.db.models.deletion.PROTECT, related_name='houses', to='addresses.street', verbose_name='Улица'),
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Уникальный идентификатор')),
                ('microdistrict', models.CharField(blank=True, help_text='Микрорайон (если применимо)', max_length=100, null=True, verbose_name='Микрорайон')),
                ('index', models.CharField(blank=True, help_text='6-значный почтовый индекс', max_length=6, null=True, validators=[django.core.validators.RegexValidator('^\\d{6}$', 'Индекс должен содержать 6 цифр')], verbose_name='Почтовый индекс')),
                ('latitude', models.CharField(blank=True, help_text='Географическая широта места расположения объекта', max_length=20, null=True, verbose_name='Широта')),
                ('longitude', models.CharField(blank=True, help_text='Географическая долгота места расположения объекта', max_length=20, null=True, verbose_name='Долгота')),
                ('administrative_unit', models.ForeignKey(blank=True, help_text='Район или округ в городе', null=True, on_delete=django.db.models.deletion.PROTECT, to='addresses.administrativeterritorialunit', verbose_name='Административно-территориальная единица')),
                ('administrative_territory', models.ForeignKey(blank=True, help_text='Административный округ (для крупных городов)', null=True, on_delete=django.db.models.deletion.PROTECT, to='addresses.administrativeterritory', verbose_name='Административный округ')),
                ('building', models.ForeignKey(blank=True, help_text='Строение или корпус', null=True, on_delete=django.db.models.deletion.PROTECT, to='addresses.building', verbose_name='Строение')),
                ('city', models.ForeignKey(blank=True, help_text='Населенный пункт', null=True, on_delete=django.db.models.deletion.PROTECT, to='addresses.city', verbose_name='Город')),
                ('coordinates', models.ForeignKey(blank=True, help_text='Координаты расположения магазина ', null=True, on_delete=django.db.models.deletion.PROTECT, to='addresses.coordinates', verbose_name='Координаты')),
                ('country', models.ForeignKey(blank=True, help_text='Страна (автоматически заполняется из иерархии)', null=True, on_delete=django.db.models.deletion.PROTECT, to='addresses.country', verbose_name='Страна')),
                ('federal_district', models.ForeignKey(blank=True, help_text='Федеральный округ (автоматически заполняется из иерархии)', null=True, on_delete=django.db.models.deletion.PROTECT, to='addresses.federaldistrict', verbose_name='Федеральный округ')),
                ('house', models.ForeignKey(blank=True, help_text='Дом (здание)', null=True, on_delete=django.db.models.deletion.PROTECT, to='addresses.house', verbose_name='Дом')),
                ('region', models.ForeignKey(blank=True, help_text='Регион (субъект федерации)', null=True, on_delete=django.db.models.deletion.PROTECT, to='addresses.region', verbose_name='Регион')),
                ('street', models.ForeignKey(blank=True, help_text='Улица, проспект, переулок и т.д.', null=True, on_delete=django.db.models.deletion.PROTECT, to='addresses.street', verbose_name='Улица')),
            ],
            options={
                'verbose_name': 'Адрес',
                'verbose_name_plural': 'Адреса',
                'db_table': 'addresses_address',
                'ordering': ['country__name', 'region__name', 'city__name', 'street__name', 'house__number', 'building__number'],
            },
        ),
        migrations.CreateModel(
            name='StreetType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Уникальный идентификатор')),
                ('name', models.CharField(help_text='Тип улицы (улица, проспект, переулок и т.д.)', max_length=255, unique=True, verbose_name='Тип улицы')),
                ('abbreviated_name', models.CharField(blank=True, help_text='Сокращенное обозначение типа (ул., пр., пер. и т.д.)', max_length=50, null=True, verbose_name='Сокращённое наименование')),
                ('show_before_name', models.BooleanField(default=True, help_text="Если отмечено: 'ул. Ленина', если нет: 'Ленина ул.'", verbose_name='Отображать тип до наименования')),
            ],
            options={
                'verbose_name': 'Тип улицы',
                'verbose_name_plural': 'Типы улиц',
                'db_table': 'addresses_street_type',
                'ordering': ['name'],
                'indexes': [django.contrib.postgres.indexes.BTreeIndex(fields=['name'], name='street_type_name_idx'), django.contrib.postgres.indexes.GinIndex(fields=['name'], name='street_type_name_gin_idx', opclasses=['gin_trgm_ops'])],
            },
        ),
        migrations.AddField(
            model_name='street',
            name='street_type',
            field=models.ForeignKey(blank=True, help_text='Тип улицы (если известен)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='streets', to='addresses.streettype', verbose_name='Тип улицы'),
        ),
        migrations.CreateModel(
            name='Timezone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Уникальный идентификатор')),
                ('name', models.CharField(help_text='Название часового пояса (например, Московское время)', max_length=255, unique=True, verbose_name='Наименование часового пояса')),
                ('offset_utc', models.IntegerField(help_text='Смещение относительно времени по Гринвичу в часах (например: +3, +5, -2)', verbose_name='Смещение относительно UTC')),
                ('offset_moscow', models.IntegerField(help_text='Смещение относительно московского времени в часах (например: 0, +2, -1)', verbose_name='Смещение относительно Москвы')),
            ],
            options={
                'verbose_name': 'Часовой пояс',
                'verbose_name_plural': 'Часовые пояса',
                'db_table': 'addresses_timezone',
                'ordering': ['offset_utc'],
                'indexes': [django.contrib.postgres.indexes.BTreeIndex(fields=['offset_utc'], name='timezone_offset_idx'), django.contrib.postgres.indexes.GinIndex(fields=['name'], name='timezone_name_gin_idx', opclasses=['gin_trgm_ops'])],
            },
        ),
        migrations.AddField(
            model_name='region',
            name='timezone',
            field=models.ForeignKey(blank=True, help_text='Часовой пояс региона (если отличается от стандартного)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='regions', to='addresses.timezone', verbose_name='Часовой пояс'),
        ),
        migrations.AddField(
            model_name='city',
            name='timezone',
            field=models.ForeignKey(blank=True, help_text='Часовой пояс города (если отличается от регионального)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cities', to='addresses.timezone', verbose_name='Часовой пояс'),
        ),
        migrations.CreateModel(
            name='TypeRegion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Уникальный идентификатор')),
                ('name', models.CharField(help_text='Полное название типа региона (область, край, республика и т.д.)', max_length=255, unique=True, verbose_name='Тип региона')),
                ('abbreviated_name', models.CharField(help_text='Сокращенное название типа (обл., кр., респ. и т.д.)', max_length=50, verbose_name='Сокращенное название')),
                ('show_before_name', models.BooleanField(default=False, help_text="Если отмечено: 'Область Московская', если нет: 'Московская область'", verbose_name='Тип перед названием')),
                ('skip_in_name', models.BooleanField(default=False, help_text='Не отображать тип региона при выводе полного названия', verbose_name='Пропускать тип в названии')),
            ],
            options={
                'verbose_name': 'Тип региона',
                'verbose_name_plural': 'Типы регионов',
                'db_table': 'addresses_type_region',
                'ordering': ['name'],
                'indexes': [django.contrib.postgres.indexes.BTreeIndex(fields=['name'], name='type_region_name_idx'), django.contrib.postgres.indexes.GinIndex(fields=['name'], name='type_region_name_gin_idx', opclasses=['gin_trgm_ops'])],
            },
        ),
        migrations.AddField(
            model_name='region',
            name='type_region',
            field=models.ForeignKey(help_text='Тип региона (область, край, республика и т.д.)', on_delete=django.db.models.deletion.PROTECT, related_name='regions', to='addresses.typeregion', verbose_name='Тип региона'),
        ),
        migrations.AddIndex(
            model_name='administrativeterritory',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['name'], name='admin_territory_name_idx'),
        ),
        migrations.AddIndex(
            model_name='administrativeterritory',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['city', 'name'], name='admin_territory_city_name_idx'),
        ),
        migrations.AddIndex(
            model_name='administrativeterritory',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='admin_territory_name_gin_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AlterUniqueTogether(
            name='administrativeterritory',
            unique_together={('city', 'name')},
        ),
        migrations.AddIndex(
            model_name='administrativeterritorialunit',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['name'], name='admin_unit_name_idx'),
        ),
        migrations.AddIndex(
            model_name='administrativeterritorialunit',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['city', 'name'], name='admin_unit_city_name_idx'),
        ),
        migrations.AddIndex(
            model_name='administrativeterritorialunit',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='admin_unit_name_gin_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AlterUniqueTogether(
            name='administrativeterritorialunit',
            unique_together={('city', 'name')},
        ),
        migrations.AddIndex(
            model_name='federaldistrict',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['name'], name='federal_district_name_idx'),
        ),
        migrations.AddIndex(
            model_name='federaldistrict',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['country', 'name'], name='federal_distr_country_name_idx'),
        ),
        migrations.AddIndex(
            model_name='federaldistrict',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='federal_district_name_gin_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AlterUniqueTogether(
            name='federaldistrict',
            unique_together={('country', 'name')},
        ),
        migrations.AddIndex(
            model_name='building',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['number'], name='building_number_idx'),
        ),
        migrations.AddIndex(
            model_name='building',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['house', 'number'], name='building_house_number_idx'),
        ),
        migrations.AddIndex(
            model_name='building',
            index=django.contrib.postgres.indexes.GinIndex(fields=['number'], name='building_number_gin_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AlterUniqueTogether(
            name='building',
            unique_together={('house', 'number')},
        ),
        migrations.AddIndex(
            model_name='house',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['number'], name='house_number_idx'),
        ),
        migrations.AddIndex(
            model_name='house',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['street', 'number'], name='house_street_number_idx'),
        ),
        migrations.AddIndex(
            model_name='house',
            index=django.contrib.postgres.indexes.GinIndex(fields=['number'], name='house_number_gin_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AlterUniqueTogether(
            name='house',
            unique_together={('street', 'number')},
        ),
        migrations.AddIndex(
            model_name='address',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['country'], name='address_country_idx'),
        ),
        migrations.AddIndex(
            model_name='address',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['region'], name='address_region_idx'),
        ),
        migrations.AddIndex(
            model_name='address',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['city'], name='address_city_idx'),
        ),
        migrations.AddIndex(
            model_name='address',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['street'], name='address_street_idx'),
        ),
        migrations.AddIndex(
            model_name='address',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['house'], name='address_house_idx'),
        ),
        migrations.AddIndex(
            model_name='address',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['building'], name='address_building_idx'),
        ),
        migrations.AddIndex(
            model_name='address',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['country', 'region'], name='address_country_region_idx'),
        ),
        migrations.AddIndex(
            model_name='address',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['region', 'city'], name='address_region_city_idx'),
        ),
        migrations.AddIndex(
            model_name='address',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['city', 'street'], name='address_city_street_idx'),
        ),
        migrations.AddIndex(
            model_name='address',
            index=django.contrib.postgres.indexes.GinIndex(fields=['index'], name='address_index_gin_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='street',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['name'], name='street_name_idx'),
        ),
        migrations.AddIndex(
            model_name='street',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['city', 'name'], name='street_city_name_idx'),
        ),
        migrations.AddIndex(
            model_name='street',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='street_name_gin_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AlterUniqueTogether(
            name='street',
            unique_together={('city', 'name')},
        ),
        migrations.AddIndex(
            model_name='city',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['name'], name='city_name_idx'),
        ),
        migrations.AddIndex(
            model_name='city',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['region', 'name'], name='city_region_name_idx'),
        ),
        migrations.AddIndex(
            model_name='city',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='city_name_gin_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AlterUniqueTogether(
            name='city',
            unique_together={('region', 'name')},
        ),
        migrations.AddIndex(
            model_name='region',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['name'], name='region_name_idx'),
        ),
        migrations.AddIndex(
            model_name='region',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['federal_district', 'name'], name='region_fd_name_idx'),
        ),
        migrations.AddIndex(
            model_name='region',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='region_name_gin_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AlterUniqueTogether(
            name='region',
            unique_together={('federal_district', 'name')},
        ),
    ]
