# Generated by Django 6.0.1 on 2026-06-02 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='slug',
            field=models.SlugField(blank=True, help_text='Название населенного пункта (АВТО)', max_length=255, null=True, verbose_name='Наименование города - транслит'),
        ),
    ]
