# Generated by Django 6.0.1 on 2026-06-02 03:47
import re
from django.db import migrations
from transliterate import translit


def populate_city_slugs(apps, schema_editor):
    City = apps.get_model('addresses', 'City')
    for city in City.objects.all():
        try:
            name_latin = translit(city.name, 'ru', reversed=True)
        except Exception:
            name_latin = city.name

        base = re.sub(r'[^\w\s-]', '', name_latin.lower()).strip()
        base = re.sub(r'[\s_-]+', '-', base) or str(city.id)[:8]
        slug = base[:90]

        if City.objects.filter(slug=slug).exclude(id=city.id).exists():
            slug = f"{slug[:85]}-{str(city.id)[:8]}"

        city.slug = slug
        city.save()


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0002_city_slug'),
    ]

    operations = [
        migrations.RunPython(populate_city_slugs, migrations.RunPython.noop),
    ]
