# Generated by Django 6.0.1 on 2026-06-02 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0003_populate_city_slugs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='slug',
            field=models.SlugField(blank=True, default='', help_text='Название населенного пункта (АВТО)', max_length=255, verbose_name='Наименование города - транслит'),
            preserve_default=False,
        ),
    ]
