# Generated by Django 6.0.1 on 2026-10-07 09:51

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0005_align_international_address_schema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='index',
            field=models.CharField(blank=True, help_text='Почтовый индекс в национальном формате страны', max_length=20, null=True, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9][A-Za-z0-9 -]{0,19}$', 'Почтовый индекс может содержать буквы, цифры, пробелы и дефисы')], verbose_name='Почтовый индекс'),
        ),
        migrations.AlterField(
            model_name='country',
            name='iso3_code',
            field=models.CharField(blank=True, help_text='Например, RUS, USA, DEU.', max_length=3, null=True, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z]{3}$', 'Используйте трёхбуквенный код ISO в верхнем регистре')], verbose_name='Код страны ISO 3166-1 alpha-3'),
        ),
        migrations.AlterField(
            model_name='country',
            name='iso_code',
            field=models.CharField(blank=True, db_index=True, help_text='Например, RU, US, DE. Поле временно допускает NULL для уже загруженных стран.', max_length=2, null=True, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z]{2}$', 'Используйте двухбуквенный код ISO в верхнем регистре')], verbose_name='Код страны ISO 3166-1 alpha-2'),
        ),
        migrations.AlterField(
            model_name='region',
            name='country',
            field=models.ForeignKey(help_text='Страна, которой принадлежит административная единица', on_delete=django.db.models.deletion.PROTECT, related_name='regions', to='addresses.country', verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='region',
            name='federal_district',
            field=models.ForeignKey(blank=True, help_text='Факультативный промежуточный уровень для стран, где он используется', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='regions', to='addresses.federaldistrict', verbose_name='Федеральный округ'),
        ),
        migrations.AlterField(
            model_name='region',
            name='type_region',
            field=models.ForeignKey(blank=True, help_text='Тип региона (область, край, республика и т.д.)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='regions', to='addresses.typeregion', verbose_name='Тип региона'),
        ),
    ]
