# Generated by Django 6.0.1 on 2026-03-30 10:39

import api.base_objects
import django.db.models.deletion
import django.db.models.manager
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('counterparties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', api.base_objects.UUIDPKField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Уникальный идентификатор')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('is_active', models.BooleanField(default=True, verbose_name='Актуальность')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('start_period', models.DateField(blank=True, null=True, verbose_name='Начало периода')),
                ('end_period', models.DateField(blank=True, null=True, verbose_name='Окончание периода')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('code1c', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Код 1с')),
                ('counterparty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='counterparties.counterparty', verbose_name='Контрагент')),
            ],
            options={
                'verbose_name': 'Акции',
                'verbose_name_plural': 'Акции',
                'db_table': 'promotions',
                'ordering': ('-created',),
            },
            managers=[
                ('active', django.db.models.manager.Manager()),
            ],
        ),
    ]
