# Generated by Django 6.0.1 on 2026-03-30 10:39

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('promotions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='Создатель'),
        ),
        migrations.AddIndex(
            model_name='promotion',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='promotion_name_gin_idx', opclasses=['gin_trgm_ops']),
        ),
    ]
