# Generated by Django 5.0.3 on 2024-04-01 03:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nomenclatures', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=uuid.uuid4, max_length=255, null=True, verbose_name='Наименование')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Уникальный идентификатор')),
                ('parameters', models.JSONField(blank=True, null=True, verbose_name='Параметры')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Ожидает обработки'), (1, 'В обработке'), (2, 'Выполнена'), (3, 'Отменена'), (4, 'Ошибка')], verbose_name='Статус')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Время выполнения')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='nomenclatures.nomenclature', verbose_name='Целевая рабочая станция')),
            ],
        ),
    ]
