# Generated by Django 5.0.3 on 2024-05-03 04:13

import django.contrib.postgres.fields.hstore
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nomenclatures', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('order_type', models.CharField(blank=True, choices=[(0, 'Реклама'), (1, 'Фоновая музыка'), (2, 'Фоновые видео'), (3, 'Фоновые картинки'), (4, 'Бегущая строка')], null=True, unique=True, verbose_name='Тип заказа')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Уникальный идентификатор')),
                ('parameters', django.contrib.postgres.fields.hstore.HStoreField(blank=True, null=True, verbose_name='Параметры')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Ожидает обработки'), (1, 'В обработке'), (2, 'Выполнена'), (3, 'Отменена'), (4, 'Ошибка')], default=0, verbose_name='Статус')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Время выполнения')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='nomenclatures.nomenclature', verbose_name='Целевая рабочая станция')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to=settings.AUTH_USER_MODEL, verbose_name='Кто создал')),
                ('type', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='tasks.type', verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Репликация',
                'verbose_name_plural': 'Репликации',
                'db_table': 'task',
            },
        ),
    ]
