# Generated by Django 5.0.3 on 2024-03-29 08:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to=settings.AUTH_USER_MODEL, verbose_name='Кто создал'),
        ),
        migrations.AddField(
            model_name='task',
            name='task_type',
            field=models.ManyToManyField(related_name='files', to='tasks.tasktype', verbose_name='Тематика'),
        ),
    ]
