# Generated by Django 5.0.3 on 2024-05-14 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='order_type',
            field=models.CharField(blank=True, choices=[(1, 'Фоновая музыка'), (2, 'Фоновые видео'), (3, 'Фоновые картинки'), (4, 'Бегущая строка')], null=True, unique=True, verbose_name='Тип заказа'),
        ),
    ]
