# Generated by Django 6.0.1 on 2026-04-15 10:17

import api.base_objects
import django.contrib.postgres.fields
import django.db.models.deletion
import django.db.models.manager
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nomenclatures', '0006_remove_nomenclaturetenant_unique_nomenclature_tenant_brand_floor_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlacementOrder',
            fields=[
                ('id', api.base_objects.UUIDPKField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Уникальный идентификатор')),
                ('duration', models.PositiveIntegerField(verbose_name='Кол-во дней')),
                ('all_days', models.BooleanField(default=True, verbose_name='Все дни недели')),
                ('days_of_week', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('mon', 'Понедельник'), ('tue', 'Вторник'), ('wed', 'Среда'), ('thu', 'Четверг'), ('fri', 'Пятница'), ('sat', 'Суббота'), ('sun', 'Воскресенье')], max_length=3), blank=True, default=list, verbose_name='Дни недели')),
                ('is_active', models.BooleanField(default=True, verbose_name='Актуальность')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placement_orders', to=settings.AUTH_USER_MODEL, verbose_name='КЛ')),
            ],
            options={
                'verbose_name': 'Заказ на размещение',
                'verbose_name_plural': 'Заказы на размещение',
            },
            managers=[
                ('active', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='PlacementOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomenclature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='nomenclatures.nomenclature', verbose_name='Место')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='placement_order.placementorder', verbose_name='Заказ')),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='placement_order_items', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный за размещение')),
            ],
            options={
                'verbose_name': 'Место',
                'verbose_name_plural': 'Места',
                'unique_together': {('order', 'nomenclature')},
            },
        ),
        migrations.AddField(
            model_name='placementorder',
            name='nomenclatures',
            field=models.ManyToManyField(related_name='placement_orders', through='placement_order.PlacementOrderItem', to='nomenclatures.nomenclature', verbose_name='Места размещения'),
        ),
    ]
