# Generated by Django 5.0.3 on 2024-04-01 03:14

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nomenclature',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Уникальный идентификатор')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('timezone', models.CharField(choices=[('Etc/GMT+11', 'UTC-11'), ('Etc/GMT+10', 'UTC-10'), ('Etc/GMT+9', 'UTC-9'), ('Etc/GMT+8', 'UTC-8'), ('Etc/GMT+7', 'UTC-7'), ('Etc/GMT+6', 'UTC-6'), ('Etc/GMT+5', 'UTC-5'), ('Etc/GMT+4', 'UTC-4'), ('Etc/GMT+3', 'UTC-3'), ('Etc/GMT+2', 'UTC-2'), ('Etc/GMT+1', 'UTC-1'), ('Etc/GMT+0', 'UTC'), ('Etc/GMT-1', 'UTC+1'), ('Etc/GMT-2', 'UTC+2'), ('Etc/GMT-3', 'UTC+3'), ('Etc/GMT-4', 'UTC+4'), ('Etc/GMT-5', 'UTC+5'), ('Etc/GMT-6', 'UTC+6'), ('Etc/GMT-7', 'UTC+7'), ('Etc/GMT-8', 'UTC+8'), ('Etc/GMT-9', 'UTC+9'), ('Etc/GMT-10', 'UTC+10'), ('Etc/GMT-11', 'UTC+11'), ('Etc/GMT-12', 'UTC+12')], default='Etc/GMT-7', max_length=31, verbose_name='Часовой пояс')),
                ('is_active', models.BooleanField(default=True, verbose_name='Актуальность номенклтауры')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Online'), (1, 'Offline 5+ minutes'), (2, 'Offline 1+ hour')], default=2, verbose_name='Статус')),
                ('version', models.CharField(max_length=127, verbose_name='Версия ПО')),
                ('description', models.TextField(verbose_name='Описание')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
        ),
        migrations.CreateModel(
            name='NomenclatureGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(choices=[(1, 'Понедельник'), (2, 'Вторник'), (3, 'Среда'), (4, 'Четверг'), (5, 'Пятница'), (6, 'Суббота'), (7, 'Воскресенье')]), size=7, verbose_name='Дни недели')),
                ('start_time', models.TimeField(verbose_name='Время начала работы')),
                ('end_time', models.TimeField(verbose_name='Время оончания работы')),
                ('volumes', models.JSONField(verbose_name='Настройки громкости')),
                ('default_volume', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(100)]), size=4, verbose_name='Громкость по умолчанию')),
            ],
        ),
        migrations.CreateModel(
            name='StatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_time', models.DateTimeField(auto_now_add=True, verbose_name='Время изменения статуса')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Online'), (1, 'Offline 5+ minutes'), (2, 'Offline 1+ hour')], verbose_name='Статус')),
            ],
        ),
        migrations.CreateModel(
            name='HardWareInfo',
            fields=[
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='nomenclature_hwinfo', serialize=False, to='nomenclatures.nomenclature', verbose_name='Номенклатура')),
                ('Citi', models.CharField(max_length=255, verbose_name='Город')),
                ('model', models.CharField(max_length=255, verbose_name='Модель')),
                ('internet_service_provider', models.CharField(max_length=255, verbose_name='Интернет провайдер')),
                ('external_ip', models.GenericIPAddressField(verbose_name='IP адресс')),
                ('network_config', models.JSONField(verbose_name='Настройки сети')),
                ('audio_device', models.JSONField(verbose_name='Звуковые карты')),
            ],
        ),
    ]
