# Generated by Django 5.0.3 on 2024-11-19 14:39

import api.base_objects
import django.contrib.postgres.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nomenclature',
            fields=[
                ('id', api.base_objects.UUIDPKField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Уникальный идентификатор')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('is_active', models.BooleanField(default=True, verbose_name='Актуальность')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('article', api.base_objects.Article(unique=True)),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('timezone', models.CharField(choices=[('Etc/GMT+11', 'UTC -11'), ('Etc/GMT+10', 'UTC -10'), ('Etc/GMT+9', 'UTC -9'), ('Etc/GMT+8', 'UTC -8'), ('Etc/GMT+7', 'UTC -7'), ('Etc/GMT+6', 'UTC -6'), ('Etc/GMT+5', 'UTC -5'), ('Etc/GMT+4', 'UTC -4'), ('Etc/GMT+3', 'UTC -3'), ('Etc/GMT+2', 'UTC -2'), ('Etc/GMT+1', 'UTC -1'), ('Etc/GMT+0', 'UTC'), ('Etc/GMT-1', 'UTC +1'), ('Etc/GMT-2', 'UTC +2'), ('Etc/GMT-3', 'UTC +3'), ('Etc/GMT-4', 'UTC +4'), ('Etc/GMT-5', 'UTC +5'), ('Etc/GMT-6', 'UTC +6'), ('Etc/GMT-7', 'UTC +7'), ('Etc/GMT-8', 'UTC +8'), ('Etc/GMT-9', 'UTC +9'), ('Etc/GMT-10', 'UTC +10'), ('Etc/GMT-11', 'UTC +11'), ('Etc/GMT-12', 'UTC +12')], default='Etc/GMT-7', max_length=31, verbose_name='Часовой пояс')),
                ('version', models.CharField(max_length=127, verbose_name='Версия ПО')),
                ('settings', models.JSONField(validators=[django.contrib.postgres.validators.KeysValidator(keys=('mon', 'tue', 'wed', 'thu', 'fri', 'sat', 'sun'), strict=True)], verbose_name='Настройки вещания')),
                ('hw_info', models.JSONField(blank=True, null=True, verbose_name='Информация о железе')),
            ],
            options={
                'verbose_name': 'Номенклатура',
                'verbose_name_plural': 'Номенклатуры',
                'db_table': 'nomenclature',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='NomenclatureAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_answer_date', models.DateTimeField(verbose_name='Время последнего ответа')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Online'), (1, 'Offline 5+ minutes'), (2, 'Offline 1+ hour')], default=2, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Время последнего ответа',
                'verbose_name_plural': 'Время последнего ответа',
                'db_table': 'availability',
                'ordering': ('-last_answer_date',),
            },
        ),
        migrations.CreateModel(
            name='StatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_time', models.DateTimeField(auto_now_add=True, verbose_name='Время изменения статуса')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Online'), (1, 'Offline 5+ minutes'), (2, 'Offline 1+ hour')], verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'История доступности',
                'verbose_name_plural': 'История доступности',
                'db_table': 'status_history',
                'ordering': ('-change_time',),
            },
        ),
    ]
