# Generated by Django 5.0.3 on 2024-05-14 02:55

import django.contrib.postgres.fields.hstore
import django.contrib.postgres.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nomenclature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Уникальный идентификатор')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('timezone', models.CharField(choices=[('Etc/GMT+11', 'UTC -11'), ('Etc/GMT+10', 'UTC -10'), ('Etc/GMT+9', 'UTC -9'), ('Etc/GMT+8', 'UTC -8'), ('Etc/GMT+7', 'UTC -7'), ('Etc/GMT+6', 'UTC -6'), ('Etc/GMT+5', 'UTC -5'), ('Etc/GMT+4', 'UTC -4'), ('Etc/GMT+3', 'UTC -3'), ('Etc/GMT+2', 'UTC -2'), ('Etc/GMT+1', 'UTC -1'), ('Etc/GMT+0', 'UTC'), ('Etc/GMT-1', 'UTC +1'), ('Etc/GMT-2', 'UTC +2'), ('Etc/GMT-3', 'UTC +3'), ('Etc/GMT-4', 'UTC +4'), ('Etc/GMT-5', 'UTC +5'), ('Etc/GMT-6', 'UTC +6'), ('Etc/GMT-7', 'UTC +7'), ('Etc/GMT-8', 'UTC +8'), ('Etc/GMT-9', 'UTC +9'), ('Etc/GMT-10', 'UTC +10'), ('Etc/GMT-11', 'UTC +11'), ('Etc/GMT-12', 'UTC +12')], default='Etc/GMT-7', max_length=31, verbose_name='Часовой пояс')),
                ('is_active', models.BooleanField(default=True, verbose_name='Актуальность номенклтауры')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Online'), (1, 'Offline 5+ minutes'), (2, 'Offline 1+ hour')], default=2, verbose_name='Статус')),
                ('version', models.CharField(max_length=127, verbose_name='Версия ПО')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('settings', django.contrib.postgres.fields.hstore.HStoreField(validators=[django.contrib.postgres.validators.KeysValidator(keys=('mon', 'tue', 'wed', 'thu', 'fri', 'sat', 'sun'), strict=True)], verbose_name='Настройки вещания')),
                ('hw_info', django.contrib.postgres.fields.hstore.HStoreField(blank=True, null=True, verbose_name='Информация о железе')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nomenclature', to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
            ],
            options={
                'verbose_name': 'Номенклатуру',
                'verbose_name_plural': 'Номенклатуры',
                'db_table': 'nomenclature',
            },
        ),
        migrations.CreateModel(
            name='NomenclatureAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_answer_date', models.DateTimeField(auto_now=True, verbose_name='Время последнего ответа')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Online'), (1, 'Offline 5+ minutes'), (2, 'Offline 1+ hour')], default=2, verbose_name='Статус')),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='nomenclatures.nomenclature', verbose_name='Рабочая станция')),
            ],
            options={
                'verbose_name': 'Время последнего ответа',
                'verbose_name_plural': 'Время последнего ответа',
                'db_table': 'availability',
            },
        ),
        migrations.CreateModel(
            name='NomenclatureGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('clients', models.ManyToManyField(related_name='nomenclature_group', to='nomenclatures.nomenclature', verbose_name='Рабочие станции')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
            ],
            options={
                'verbose_name': 'Группу',
                'verbose_name_plural': 'Группы',
                'db_table': 'group',
            },
        ),
        migrations.CreateModel(
            name='StatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_time', models.DateTimeField(auto_now_add=True, verbose_name='Время изменения статуса')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Online'), (1, 'Offline 5+ minutes'), (2, 'Offline 1+ hour')], verbose_name='Статус')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='nomenclatures.nomenclature', verbose_name='Рабочая станция')),
            ],
            options={
                'verbose_name': 'Историю доступности',
                'verbose_name_plural': 'История доступности',
                'db_table': 'status_history',
            },
        ),
    ]
