# Generated by Django 5.0.3 on 2024-05-15 10:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nomenclatures', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='nomenclature',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nomenclature', to=settings.AUTH_USER_MODEL, verbose_name='Создатель'),
        ),
        migrations.AddField(
            model_name='nomenclaturegroup',
            name='clients',
            field=models.ManyToManyField(related_name='nomenclature_group', to='nomenclatures.nomenclature', verbose_name='Рабочие станции'),
        ),
        migrations.AddField(
            model_name='nomenclaturegroup',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Создатель'),
        ),
        migrations.AddField(
            model_name='nomenclature',
            name='settings',
            field=models.ManyToManyField(blank=True, related_name='nomenclature_settings', to='nomenclatures.settings', verbose_name='Настройки вещания'),
        ),
        migrations.AddField(
            model_name='statushistory',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nomenclatures.nomenclature', verbose_name='Рабочая станция'),
        ),
    ]
