# Generated by Django 5.0.3 on 2024-05-07 02:21

import django.contrib.postgres.fields.hstore
import django.contrib.postgres.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclatures', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nomenclaturegroup',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='volumes',
            field=django.contrib.postgres.fields.hstore.HStoreField(validators=[django.contrib.postgres.validators.KeysValidator(keys=['start', 'end', 'volumes'])], verbose_name='Настройки громкости'),
        ),
    ]
