# Generated by Django 5.0.3 on 2024-11-19 14:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nomenclatures', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='nomenclature',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='Создатель'),
        ),
        migrations.AddField(
            model_name='nomenclatureavailability',
            name='client',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='nomenclatures.nomenclature', verbose_name='Рабочая станция'),
        ),
        migrations.AddField(
            model_name='statushistory',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='nomenclatures.nomenclature', verbose_name='Рабочая станция'),
        ),
        migrations.AddConstraint(
            model_name='nomenclature',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_nomenclature_name', violation_error_message='Номенклатура с таким названием уже существует'),
        ),
    ]
