# Generated by Django 6.0.1 on 2026-03-30 10:39

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('addresses', '0001_initial'),
        ('counterparties', '0002_initial'),
        ('nomenclatures', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='nomenclature',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='Создатель'),
        ),
        migrations.AddField(
            model_name='nomenclature',
            name='responsible_ad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ad_nomenclature', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный за размещение'),
        ),
        migrations.AddField(
            model_name='nomenclature',
            name='responsible_placement_marketing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='placement_marketing_nomenclature', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный за маркетинг размещения'),
        ),
        migrations.AddField(
            model_name='nomenclature',
            name='responsible_radio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='radio_nomenclature', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный за радио'),
        ),
        migrations.AddField(
            model_name='nomenclature',
            name='responsible_technic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='technic_nomenclature', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный за технику'),
        ),
        migrations.AddField(
            model_name='nomenclature',
            name='responsible_technic_on_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='technic_on_address_nomenclature', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный за технику на адресе'),
        ),
        migrations.AddField(
            model_name='nomenclatureavailability',
            name='client',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='nomenclatures.nomenclature', verbose_name='Рабочая станция'),
        ),
        migrations.AddField(
            model_name='nomenclatureimage',
            name='nomenclature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='nomenclatures.nomenclature', verbose_name='Номенклатура'),
        ),
        migrations.AddField(
            model_name='nomenclaturetenant',
            name='nomenclature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nomenclature_tenants', to='nomenclatures.nomenclature', verbose_name='Номенклатура'),
        ),
        migrations.AddField(
            model_name='nomenclaturetenant',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_nomenclatures', to='counterparties.counterparty', verbose_name='Арендатор'),
        ),
        migrations.AddField(
            model_name='nomenclature',
            name='tenants',
            field=models.ManyToManyField(related_name='rented_nomenclatures', through='nomenclatures.NomenclatureTenant', to='counterparties.counterparty', verbose_name='Арендаторы'),
        ),
        migrations.AddField(
            model_name='statushistory',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='nomenclatures.nomenclature', verbose_name='Рабочая станция'),
        ),
        migrations.AddField(
            model_name='nomenclature',
            name='typeOfPlace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='type_nomenclature', to='nomenclatures.typeofplace', verbose_name='Тип места размещения'),
        ),
        migrations.AddField(
            model_name='nomenclatureaddress',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='addresses.address', verbose_name='Адрес из справочника'),
        ),
        migrations.AddIndex(
            model_name='nomenclaturetenant',
            index=models.Index(fields=['nomenclature'], name='nomenclatur_nomencl_bd917c_idx'),
        ),
        migrations.AddIndex(
            model_name='nomenclaturetenant',
            index=models.Index(fields=['tenant'], name='nomenclatur_tenant__d1c6f5_idx'),
        ),
        migrations.AddIndex(
            model_name='nomenclaturetenant',
            index=models.Index(fields=['tenant', 'nomenclature'], name='nomenclatur_tenant__c237f0_idx'),
        ),
        migrations.AddConstraint(
            model_name='nomenclaturetenant',
            constraint=models.UniqueConstraint(fields=('nomenclature', 'tenant'), name='unique_nomenclature_tenant'),
        ),
        migrations.AddIndex(
            model_name='nomenclature',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='nomenclature_name_gin_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='nomenclature',
            index=django.contrib.postgres.indexes.GinIndex(fields=['code1c'], name='nomenclature_code1c_gin_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='nomenclature',
            index=django.contrib.postgres.indexes.GinIndex(fields=['version'], name='nomenclature_version_gin_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='nomenclature',
            index=django.contrib.postgres.indexes.GinIndex(fields=['settings'], name='settings_gin_idx'),
        ),
        migrations.AddIndex(
            model_name='nomenclature',
            index=models.Index(fields=['typeOfPlace'], name='nomenclatur_typeOfP_98f14b_idx'),
        ),
        migrations.AddIndex(
            model_name='nomenclature',
            index=models.Index(fields=['responsible_radio'], name='nomenclatur_respons_511968_idx'),
        ),
        migrations.AddIndex(
            model_name='nomenclature',
            index=models.Index(fields=['responsible_ad'], name='nomenclatur_respons_d58eff_idx'),
        ),
        migrations.AddIndex(
            model_name='nomenclature',
            index=models.Index(condition=models.Q(('is_active', True)), fields=['brand'], name='idx_active_brand'),
        ),
        migrations.AddIndex(
            model_name='nomenclature',
            index=models.Index(fields=['legalEntity'], name='nomenclatur_legalEn_a92c40_idx'),
        ),
        migrations.AddIndex(
            model_name='nomenclature',
            index=models.Index(fields=['responsible_technic'], name='nomenclatur_respons_a5a575_idx'),
        ),
        migrations.AddIndex(
            model_name='nomenclature',
            index=models.Index(fields=['responsible_technic_on_address'], name='nomenclatur_respons_1faa33_idx'),
        ),
        migrations.AddIndex(
            model_name='nomenclature',
            index=models.Index(fields=['responsible_placement_marketing'], name='nomenclatur_respons_7957c6_idx'),
        ),
        migrations.AddIndex(
            model_name='nomenclature',
            index=models.Index(fields=['code1c'], name='nomenclatur_code1c_53ccfb_idx'),
        ),
        migrations.AddIndex(
            model_name='nomenclature',
            index=models.Index(fields=['timezone'], name='nomenclatur_timezon_bfbe80_idx'),
        ),
        migrations.AddIndex(
            model_name='nomenclature',
            index=models.Index(fields=['version'], name='nomenclatur_version_880be6_idx'),
        ),
        migrations.AddIndex(
            model_name='nomenclature',
            index=models.Index(fields=['pricePerMonth'], name='nomenclatur_pricePe_4bdf5b_idx'),
        ),
        migrations.AddIndex(
            model_name='nomenclature',
            index=models.Index(fields=['-created'], name='nomenclatur_created_509f3e_idx'),
        ),
        migrations.AddIndex(
            model_name='nomenclature',
            index=models.Index(fields=['brand', 'typeOfPlace'], name='nomenclatur_brand_i_11e644_idx'),
        ),
        migrations.AddIndex(
            model_name='nomenclature',
            index=models.Index(fields=['legalEntity', 'brand'], name='nomenclatur_legalEn_7508cd_idx'),
        ),
        migrations.AddConstraint(
            model_name='nomenclature',
            constraint=models.UniqueConstraint(fields=('code1c',), name='unique_nomenclature_name', violation_error_message='Номенклатура с таким кодом уже существует'),
        ),
    ]
