# Generated by Django 5.0.3 on 2024-05-06 07:55

import django.contrib.postgres.fields.hstore
import django.contrib.postgres.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclatures', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nomenclature',
            name='last_answer_date',
        ),
        migrations.AlterField(
            model_name='nomenclature',
            name='hw_info',
            field=django.contrib.postgres.fields.hstore.HStoreField(blank=True, null=True, verbose_name='Информация о железе'),
        ),
        migrations.AlterField(
            model_name='nomenclature',
            name='settings',
            field=django.contrib.postgres.fields.hstore.HStoreField(validators=[django.contrib.postgres.validators.KeysValidator(keys=('mon', 'tue', 'wed', 'thu', 'fri', 'sat', 'sun'), strict=True)], verbose_name='Настройки вещания'),
        ),
        migrations.CreateModel(
            name='NomenclatureAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_answer_date', models.DateTimeField(auto_now=True, verbose_name='Время последнего ответа')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Online'), (1, 'Offline 5+ minutes'), (2, 'Offline 1+ hour')], default=2, verbose_name='Статус')),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='nomenclatures.nomenclature', verbose_name='Рабочая станция')),
            ],
            options={
                'verbose_name': 'Время последнего ответа',
            },
        ),
    ]
