# Generated by Django 5.0.3 on 2024-04-02 07:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclatures', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nomenclature',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Уникальный идентификатор'),
        ),
    ]
