# Generated by Django 6.0.1 on 2026-03-30 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclatures', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='typeofplace',
            name='genitive',
        ),
        migrations.RemoveField(
            model_name='typeofplace',
            name='prepositional',
        ),
        migrations.AddField(
            model_name='typeofplace',
            name='tariff',
            field=models.CharField(blank=True, null=True, verbose_name='Для тарифа'),
        ),
        migrations.AddField(
            model_name='typeofplace',
            name='tariff_single',
            field=models.CharField(blank=True, null=True, verbose_name='Для тарифа в единственном числе'),
        ),
        migrations.AlterField(
            model_name='nomenclature',
            name='external_audio_media',
            field=models.CharField(blank=True, default='', null=True, verbose_name='Аудио носители (кол-во внеш.)'),
        ),
        migrations.AlterField(
            model_name='nomenclature',
            name='external_video_media',
            field=models.CharField(blank=True, default='', null=True, verbose_name='Видео носители (кол-во внеш.)'),
        ),
        migrations.AlterField(
            model_name='nomenclature',
            name='internal_audio_media',
            field=models.CharField(blank=True, default='', null=True, verbose_name='Аудио носители (кол-во внут.)'),
        ),
        migrations.AlterField(
            model_name='nomenclature',
            name='internal_video_media',
            field=models.CharField(blank=True, default='', null=True, verbose_name='Видео носители (кол-во внут.)'),
        ),
    ]
