# Generated by Django 5.2.3 on 2025-07-24 23:39

import uuid

import django.contrib.postgres.indexes
import django.db.models.deletion
import django_minio_backend.models
from django.conf import settings
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations, models

import nomenclatures.models


class Migration(migrations.Migration):

    dependencies = [
        ("nomenclatures", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        TrigramExtension(),
        migrations.CreateModel(
            name="NomenclatureImage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.UUID(
                            "8ec1aad2-d8ba-486b-ad03-fa3997d2b01b"
                        ),
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ИД",
                    ),
                ),
                (
                    "source",
                    models.FileField(
                        storage=django_minio_backend.models.MinioBackend(
                            bucket_name="local-media"
                        ),
                        upload_to=nomenclatures.models.media_path,
                        verbose_name="Файл",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("interior", "Интерьер"),
                            ("exterior", "Экстерьер"),
                        ],
                        max_length=31,
                        verbose_name="Тип фотографии",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
            ],
            options={
                "verbose_name": "Фотография номенклатуры",
                "verbose_name_plural": "Фотографии номенклатур",
                "db_table": "nomenclature_images",
                "ordering": ("-created",),
            },
        ),
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.UUID(
                            "36974b07-5fe6-4535-9dae-67e85f123654"
                        ),
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ИД",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255,
                        unique=True,
                        verbose_name="Наименование бренда",
                    ),
                ),
                (
                    "logo",
                    models.FileField(
                        storage=django_minio_backend.models.MinioBackend(
                            bucket_name="local-media"
                        ),
                        upload_to="brand_logo",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
            ],
            options={
                "verbose_name": "Бренд",
                "verbose_name_plural": "Бренды",
                "db_table": "brands",
                "ordering": ("-created",),
                "indexes": [
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["name"],
                        name="brand_name_gin_idx",
                        opclasses=["gin_trgm_ops"],
                    )
                ],
            },
        ),
        migrations.AddField(
            model_name="nomenclature",
            name="brand",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="nomenclatures.brand",
                verbose_name="Бренд номенклатуры",
            ),
        ),
        migrations.AddIndex(
            model_name="nomenclature",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["name"],
                name="nomenclature_name_gin_idx",
                opclasses=["gin_trgm_ops"],
            ),
        ),
        migrations.AddField(
            model_name="nomenclatureimage",
            name="nomenclature",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="images",
                to="nomenclatures.nomenclature",
                verbose_name="Номенклатура",
            ),
        ),
    ]
