# Generated by Django 5.0.3 on 2024-05-07 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclatures', '0002_remove_nomenclature_last_answer_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nomenclatureavailability',
            options={'verbose_name': 'Время последнего ответа', 'verbose_name_plural': 'Время последнего ответа'},
        ),
        migrations.AlterModelTable(
            name='nomenclatureavailability',
            table='availability',
        ),
    ]
