# Generated by Django 5.2.3 on 2025-07-30 23:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nomenclatures", "0003_nomenclatureimage_brand_nomenclature_brand_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="NomenclatureAddress",
            fields=[
                (
                    "nomenclature",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="address",
                        serialize=False,
                        to="nomenclatures.nomenclature",
                        verbose_name="Номенклатура",
                    ),
                ),
                ("city", models.CharField(max_length=255, verbose_name="Город")),
                (
                    "federalDistrict",
                    models.CharField(max_length=255, verbose_name="Федеральный округ"),
                ),
                ("street", models.CharField(max_length=255, verbose_name="Улица")),
                (
                    "street_house",
                    models.CharField(max_length=31, verbose_name="Номер дома"),
                ),
                (
                    "building",
                    models.CharField(
                        blank=True, max_length=31, null=True, verbose_name="Строение"
                    ),
                ),
            ],
            options={
                "verbose_name": "Адрес номенклатуры",
                "verbose_name_plural": "Адреса номенклатур",
                "db_table": "addresses",
            },
        ),
        migrations.AddField(
            model_name="nomenclature",
            name="contentType",
            field=models.CharField(
                choices=[
                    ("audio", "Аудио"),
                    ("video", "Видео"),
                    ("audio_video", "Аудио + Видео"),
                    ("audio_video_image", "Аудио + Видео + Картинка"),
                    ("video_image", "Видео + Картинка"),
                    ("audio_image", "Аудио + Картинка"),
                ],
                default="audio",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="nomenclature",
            name="legalEntity",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="nomenclature",
            name="pricePerMonth",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                verbose_name="Стоимость размещения в месяц",
            ),
        ),
        migrations.AddField(
            model_name="nomenclature",
            name="typeOfPlace",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Тип места размещения",
            ),
        ),
        migrations.AlterField(
            model_name="brand",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("6ccdc4b4-24a3-462a-8a20-7c2b6491f6af"),
                editable=False,
                primary_key=True,
                serialize=False,
                verbose_name="ИД",
            ),
        ),
        migrations.AlterField(
            model_name="nomenclatureimage",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("bdc46a92-4b82-41d4-8063-630ab6c8f9fd"),
                editable=False,
                primary_key=True,
                serialize=False,
                verbose_name="ИД",
            ),
        ),
    ]
