# Generated by Django 5.0.3 on 2024-04-04 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclatures', '0003_alter_nomenclature_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hardwareinfo',
            old_name='Citi',
            new_name='city',
        ),
    ]
