# Generated by Django 6.0.1 on 2026-03-30 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0001_initial'),
        ('counterparties', '0002_initial'),
        ('nomenclatures', '0003_remove_typeofplace_genitive_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nomenclaturetenant',
            name='atm',
            field=models.BooleanField(default=False, verbose_name='Банкомат/терминал'),
        ),
        migrations.AddField(
            model_name='nomenclaturetenant',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brand_tenant', to='brands.brand', verbose_name='Бренд арендатора'),
        ),
        migrations.AddIndex(
            model_name='nomenclaturetenant',
            index=models.Index(fields=['brand'], name='nomenclatur_brand_i_00cf9c_idx'),
        ),
        migrations.AddIndex(
            model_name='nomenclaturetenant',
            index=models.Index(fields=['brand', 'tenant'], name='nomenclatur_brand_i_14971f_idx'),
        ),
    ]
