# Generated by Django 5.0.3 on 2024-05-07 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclatures', '0003_alter_nomenclatureavailability_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statushistory',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='nomenclatures.nomenclature', verbose_name='Рабочая станция'),
        ),
    ]
