# Generated by Django 6.0.1 on 2026-03-30 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0001_initial'),
        ('counterparties', '0002_initial'),
        ('nomenclatures', '0004_nomenclaturetenant_atm_nomenclaturetenant_brand_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='nomenclaturetenant',
            name='unique_nomenclature_tenant',
        ),
        migrations.AddConstraint(
            model_name='nomenclaturetenant',
            constraint=models.UniqueConstraint(fields=('nomenclature', 'tenant', 'brand', 'floor'), name='unique_nomenclature_tenant_brand_floor'),
        ),
    ]
