# Generated by Django 5.0.3 on 2024-04-11 10:25

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclatures', '0004_rename_citi_hardwareinfo_city'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hardwareinfo',
            options={'verbose_name': 'Информация о железе', 'verbose_name_plural': 'Информация о железе'},
        ),
        migrations.AlterModelOptions(
            name='nomenclature',
            options={'verbose_name': 'Номенклатура', 'verbose_name_plural': 'Номенклатуры'},
        ),
        migrations.AlterModelOptions(
            name='nomenclaturegroup',
            options={'verbose_name': 'Группа', 'verbose_name_plural': 'Группы'},
        ),
        migrations.AlterModelOptions(
            name='settings',
            options={'verbose_name': 'Настройка номенклатуры', 'verbose_name_plural': 'Настройки номенклатуры'},
        ),
        migrations.AlterModelOptions(
            name='statushistory',
            options={'verbose_name': 'История доступности', 'verbose_name_plural': 'История доступности'},
        ),
        migrations.AlterField(
            model_name='settings',
            name='days',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(), size=7, verbose_name='Дни недели'),
        ),
    ]
