# Generated by Django 5.0.3 on 2024-05-13 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclatures', '0004_alter_statushistory_client'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nomenclature',
            options={'verbose_name': 'Номенклатуру', 'verbose_name_plural': 'Номенклатуры'},
        ),
        migrations.AlterModelOptions(
            name='nomenclaturegroup',
            options={'verbose_name': 'Группу', 'verbose_name_plural': 'Группы'},
        ),
        migrations.AlterModelOptions(
            name='statushistory',
            options={'verbose_name': 'Историю доступности', 'verbose_name_plural': 'История доступности'},
        ),
    ]
