# Generated by Django 5.2.3 on 2025-07-31 21:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nomenclatures", "0004_nomenclatureaddress_nomenclature_contenttype_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="brand",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("31337de0-c8ce-45dd-b4de-eaf1777fc98f"),
                editable=False,
                primary_key=True,
                serialize=False,
                verbose_name="ИД",
            ),
        ),
        migrations.AlterField(
            model_name="nomenclatureaddress",
            name="nomenclature",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                related_name="address",
                serialize=False,
                to="nomenclatures.nomenclature",
                verbose_name="Номенклатура",
            ),
        ),
        migrations.AlterField(
            model_name="nomenclatureimage",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("cc2d5859-26ee-4f5d-8fb0-18cec5935aff"),
                editable=False,
                primary_key=True,
                serialize=False,
                verbose_name="ИД",
            ),
        ),
    ]
