# Generated by Django 5.0.3 on 2024-04-12 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclatures', '0005_alter_hardwareinfo_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='hardwareinfo',
            table='hwinfo',
        ),
        migrations.AlterModelTable(
            name='nomenclature',
            table='nomenclature',
        ),
        migrations.AlterModelTable(
            name='nomenclaturegroup',
            table='group',
        ),
        migrations.AlterModelTable(
            name='statushistory',
            table='status_history',
        ),
    ]
