# Generated by Django 6.0.1 on 2026-04-13 16:51

import django.contrib.postgres.indexes
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0001_initial'),
        ('counterparties', '0002_initial'),
        ('nomenclatures', '0005_remove_nomenclaturetenant_unique_nomenclature_tenant_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='nomenclaturetenant',
            name='unique_nomenclature_tenant_brand_floor',
        ),
        migrations.AddField(
            model_name='nomenclature',
            name='for_web',
            field=models.BooleanField(default=True, verbose_name='Отображать в веб'),
        ),
        migrations.AddIndex(
            model_name='nomenclature',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='nom_name_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
    ]
