# Generated by Django 6.0.1 on 2026-04-24 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclatures', '0006_remove_nomenclaturetenant_unique_nomenclature_tenant_brand_floor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nomenclature',
            name='slots_per_hour',
            field=models.CharField(blank=True, default=1, null=True, verbose_name='Кол-во выходов в час'),
        ),
    ]
