# Generated by Django 6.0.1 on 2026-05-20 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclatures', '0007_nomenclature_slots_per_hour'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_from', models.PositiveIntegerField(help_text='Включительно', verbose_name='Дней (от)')),
                ('days_to', models.PositiveIntegerField(blank=True, help_text='Включительно. Пусто = без верхней границы', null=True, verbose_name='Дней (до)')),
                ('coefficient', models.DecimalField(decimal_places=3, help_text='Множитель цены: 1.000 = без скидки, 0.900 = скидка 10%', max_digits=4, verbose_name='Коэффициент скидки')),
                ('nomenclature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount_rules', to='nomenclatures.nomenclature', verbose_name='Номенклатура')),
            ],
            options={
                'verbose_name': 'Правило скидки',
                'verbose_name_plural': 'Правила скидок',
                'db_table': 'discount_rule',
                'ordering': ('nomenclature', 'days_from'),
                'indexes': [models.Index(fields=['nomenclature', 'days_from'], name='discount_ru_nomencl_19c303_idx')],
            },
        ),
    ]
