# Generated by Django 6.0.1 on 2026-05-22 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclatures', '0009_add_search_vector'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='nomenclature',
            new_name='nomenclatur_search__488b14_idx',
            old_name='nomenclatur_search__index',
        ),
        migrations.AlterField(
            model_name='nomenclature',
            name='search_vector',
            field=models.TextField(blank=True, db_index=True, default='', help_text='Денормализованное поле для полнотекстового поиска', verbose_name='Поисковый вектор'),
        ),
    ]
