# Generated by Django 6.0.1 on 2026-09-18 12:43

import django.db.models.deletion
import django_minio_backend.models
import nomenclatures.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclatures', '0010_rename_nomenclatur_search__index_nomenclatur_search__488b14_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nomenclatureaddress',
            options={'verbose_name': 'Адрес Номенклатуры', 'verbose_name_plural': 'Адреса Номенклатур'},
        ),
        migrations.AddField(
            model_name='nomenclature',
            name='applied_settings_revision',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='Версия подтверждённых настроек'),
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
            migrations.AddField(
                model_name="nomenclature",
                name="old_catalog_slug",
                field=models.SlugField(
                    blank=True,
                    default="",
                    help_text="Slug из старой версии каталога для редиректов",
                    max_length=512,
                    verbose_name="Старый URL slug (каталог)",
                ),
            ),
        ],
        database_operations=[],
        ),
        migrations.AddField(
            model_name='nomenclature',
            name='runtime_state',
            field=models.JSONField(blank=True, null=True, verbose_name='Текущее состояние эфира'),
        ),
        migrations.AddField(
            model_name='nomenclature',
            name='station_capabilities',
            field=models.JSONField(blank=True, editable=False, null=True, verbose_name='Доступные устройства Player'),
        ),
        migrations.AddField(
            model_name='nomenclature',
            name='visual_output_settings',
            field=models.JSONField(blank=True, editable=False, null=True, verbose_name='Подтверждённые настройки визуального вывода'),
        ),
        migrations.AlterField(
            model_name='nomenclature',
            name='for_web',
            field=models.BooleanField(default=False, verbose_name='Отображать в веб'),
        ),
        migrations.AlterField(
            model_name='nomenclature',
            name='worktime_end',
            field=models.TimeField(blank=True, null=True, verbose_name='Закрытие'),
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name="NomenclatureVideo",
                        fields=[
                            (
                              "id",
                              models.UUIDField(
                              default=uuid.uuid4,
                              editable=False,
                              primary_key=True,
                              serialize=False,
                              verbose_name="ИД",
                            ),
                        ),
                        (
                              "source",
                              models.FileField(
                                  storage=django_minio_backend.models.MinioBackend(
                                  bucket_name="local-media"
                              ),
                                  upload_to=nomenclatures.models.media_path,
                                  verbose_name="Файл",
                              ),
                        ),
                        (
                              "type",
                              models.CharField(
                                 choices=[
                                     ("interior", "Интерьер"),
                                     ("exterior", "Экстерьер"),
                                     ("signage", "Вывеска"),
                                     ("installation", "Установка"),
                                 ],
                                 max_length=31,
                                 verbose_name="Тип видеозаписи",
                              ),
                         ),
                         ("created", models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")),
                         ("hash", models.CharField(db_index=True, editable=False, max_length=64)),
                         (
                             "nomenclature",
                             models.ForeignKey(
                                 on_delete=django.db.models.deletion.CASCADE,
                                 related_name="videos",
                                 to="nomenclatures.nomenclature",
                                 verbose_name="Номенклатура",
                             ),
                           ),
                      ],
                      options={
                          "verbose_name": "Видео номенклатуры",
                          "verbose_name_plural": "Видео номенклатур",
                          "db_table": "nomenclature_videos",
                          "ordering": ("-created",),
                      },
                 ),
               ],
               database_operations=[],
        ),

        migrations.CreateModel(
            name='StationCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rotated_at', models.DateTimeField(auto_now=True)),
                ('nomenclature', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='station_credential', to='nomenclatures.nomenclature')),
            ],
            options={
                'verbose_name': 'Ключ доступа станции',
                'verbose_name_plural': 'Ключи доступа станций',
            },
        ),
        migrations.CreateModel(
            name='StationCommandV2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('kind', models.CharField(default='apply_settings_patch', max_length=64)),
                ('body', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('applied', 'Применена'), ('failed', 'Ошибка')], default='pending', max_length=16)),
                ('result', models.JSONField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nomenclature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='v2_commands', to='nomenclatures.nomenclature')),
            ],
            options={
                'verbose_name': 'Команда плеера v2',
                'verbose_name_plural': 'Команды плеера v2',
                'indexes': [models.Index(fields=['nomenclature', 'status', 'created_at'], name='nomenclatur_nomencl_7e2a54_idx')],
            },
        ),
        migrations.CreateModel(
            name='StationInstallation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rotated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='station_installations', to=settings.AUTH_USER_MODEL)),
                ('nomenclature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='station_installations', to='nomenclatures.nomenclature')),
            ],
            options={
                'verbose_name': 'Установка плеера',
                'verbose_name_plural': 'Установки плеера',
                'indexes': [models.Index(fields=['nomenclature', 'is_active'], name='nomenclatur_nomencl_48e07d_idx'), models.Index(fields=['created_by', 'is_active'], name='nomenclatur_created_64103a_idx')],
            },
        ),
        migrations.CreateModel(
            name='StatisticReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.UUIDField(verbose_name='Идентификатор события')),
                ('stat_type', models.CharField(max_length=16, verbose_name='Тип статистики')),
                ('received_at', models.DateTimeField(auto_now_add=True, verbose_name='Принято')),
                ('nomenclature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistic_receipts', to='nomenclatures.nomenclature', verbose_name='Рабочая станция')),
            ],
            options={
                'db_table': 'statistic_receipt',
                'indexes': [models.Index(fields=['received_at'], name='statistic_r_receive_bcfd59_idx')],
                'constraints': [models.UniqueConstraint(fields=('nomenclature', 'event_id'), name='unique_statistic_receipt_event')],
            },
        ),
    ]




