# Generated by Django 6.0.1 on 2026-05-29 05:10

import clickhouse_backend.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ch_statistic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adstat',
            name='played_krasnoyarsk',
            field=clickhouse_backend.models.DateTimeField(blank=True, null=True, verbose_name='Когда было проиграно (Красноярск)'),
        ),
        migrations.AddField(
            model_name='backupimagestat',
            name='played_krasnoyarsk',
            field=clickhouse_backend.models.DateTimeField(blank=True, null=True, verbose_name='Когда было проиграно (Красноярск)'),
        ),
        migrations.AddField(
            model_name='imagestat',
            name='played_krasnoyarsk',
            field=clickhouse_backend.models.DateTimeField(blank=True, null=True, verbose_name='Когда было проиграно (Красноярск)'),
        ),
        migrations.AddField(
            model_name='musicstat',
            name='played_krasnoyarsk',
            field=clickhouse_backend.models.DateTimeField(blank=True, null=True, verbose_name='Когда было проиграно (Красноярск)'),
        ),
        migrations.AddField(
            model_name='tickerstat',
            name='played_krasnoyarsk',
            field=clickhouse_backend.models.DateTimeField(blank=True, null=True, verbose_name='Когда было проиграно (Красноярск)'),
        ),
        migrations.AddField(
            model_name='videostat',
            name='played_krasnoyarsk',
            field=clickhouse_backend.models.DateTimeField(blank=True, null=True, verbose_name='Когда было проиграно (Красноярск)'),
        ),
    ]
