# Generated by Django 6.0.1 on 2026-07-07 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ch_statistic', '0002_adstat_played_krasnoyarsk_and_more'),
    ]

    operations = [
        migrations.RemoveField(model_name='adstat', name='played_krasnoyarsk'),
        migrations.RemoveField(model_name='backupimagestat', name='played_krasnoyarsk'),
        migrations.RemoveField(model_name='imagestat', name='played_krasnoyarsk'),
        migrations.RemoveField(model_name='musicstat', name='played_krasnoyarsk'),
        migrations.RemoveField(model_name='tickerstat', name='played_krasnoyarsk'),
        migrations.RemoveField(model_name='videostat', name='played_krasnoyarsk'),
    ]
