server {
  listen 80;
  server_tokens off;
  server_name 192.168.0.8;

  location /api/ {
    proxy_set_header Host $http_host;
    client_max_body_size 2048M;
    proxy_pass http://backend:8000/api/;
  }

  location /auth/ {
    proxy_set_header Host $http_host;
    client_max_body_size 20M;
    proxy_pass http://backend:8000/auth/;
  }

  #location = /maps {
  #  return 301 /maps/;
  #}

  location /maps/ {
    # Убираем слеш в конце proxy_pass (это важно!)
    proxy_pass http://tileserver:7777;
    
    proxy_http_version 1.1;
    proxy_set_header Host $http_host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    
    # Критически важно для обработки редиректов
    proxy_set_header X-Forwarded-Host $http_host;
    proxy_set_header X-Forwarded-Prefix /maps;
    
    # Перенаправляем редиректы от tileserver
    proxy_redirect http://tileserver:7777/ /maps/;
    proxy_redirect https://tileserver:7777/ /maps/;
    
    # Увеличиваем таймауты для загрузки стилей
    proxy_read_timeout 300s;
    proxy_connect_timeout 300s;
   }

  location / {
    proxy_set_header Host $http_host;
    client_max_body_size 2048M;
    proxy_pass http://backend:8000/admin/;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection 'upgrade';
    proxy_set_header Host $host;
    proxy_cache_bypass $http_upgrade;
  }

  # location / {
  #   proxy_pass http://frontend:3000;
  #   proxy_http_version 1.1;
  #   proxy_set_header Upgrade $http_upgrade;
  #   proxy_set_header Connection 'upgrade';
  #   proxy_set_header Host $host;
  #   proxy_cache_bypass $http_upgrade;
  # }

  location /local-static/ {
    proxy_pass http://files:9000;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection 'upgrade';
    proxy_set_header Host $host;
    proxy_cache_bypass $http_upgrade;
  }

  location /local-media/ {
    proxy_pass http://files:9000;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection 'upgrade';
    proxy_set_header Host $host;
    proxy_cache_bypass $http_upgrade;
  }

  location /backupvm/ {
    proxy_pass http://files:9000;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection 'upgrade';
    proxy_set_header Host $host;
    proxy_cache_bypass $http_upgrade;
  }
}
