server {
  listen 80;
  index index.html;
  server_tokens off;
  server_name 192.168.0.170;

  location /api/ {
    proxy_set_header Host $http_host;
    client_max_body_size 20M;
    proxy_pass http://backend:8000/api/;
  }
  location /auth/ {
    proxy_set_header Host $http_host;
    client_max_body_size 20M;
    proxy_pass http://backend:8000/auth/;
  }
  location /admin/ {
    proxy_set_header Host $http_host;
    client_max_body_size 20M;
    proxy_pass http://backend:8000/admin/;
  }
  location ~ ^/nomenclatures/(?!create).*/ {
     root /staticfiles/;
     rewrite ^/nomenclatures/(.*)$ /nomenclatures/[id]/index.html break;
  }
  location ~ ^/files/(?!create).*/ {
     root /staticfiles/;
     rewrite ^/files/(.*)$ /files/[id]/index.html break;
  }
  location ~ ^/orders/(?!create).*/ {
     root /staticfiles/;
     rewrite ^/orders/(.*)$ /orders/[id]/index.html break;
  }
  location ~ ^/groups/(?!create).*/ {
     root /staticfiles/;
     rewrite ^/groups/(.*)$ /groups/[id]/index.html break;
  }
  location ~ ^/playlists/(?!create).*/ {
     root /staticfiles/;
     rewrite ^/playlists/(.*)$ /playlists/[id]/index.html break;
  }
  location ~ ^/replications/(?!create).*/ {
     root /staticfiles/;
     rewrite ^/replications/(.*)$ /replications/[id]/index.html break;
  }
  location / {
    alias /staticfiles/;
    try_files $uri $uri/ index.html;
  }
}