# Generated by Django 6.0.1 on 2026-03-30 10:39

import api.base_objects
import django.db.models.deletion
import django.db.models.manager
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('addresses', '0001_initial'),
        ('brands', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CounterpartyContactInfo',
            fields=[
                ('basic', models.BooleanField(default=False, verbose_name='Основной')),
                ('type', models.CharField(blank=True, choices=[('address', 'Адрес'), ('phone', 'Телефон'), ('mail', 'Адрес электронной почты'), ('web', 'Веб-страница'), ('messenger', 'Мессенджер'), ('other', 'Другое')], max_length=255, null=True)),
                ('vidtel', models.CharField(blank=True, choices=[('mobkl', 'Телефон мобильный КЛ'), ('dop', 'Дополнительный'), ('mobkldop', 'Телефон дополнительный КЛ')], max_length=255, null=True, verbose_name='Вид телефона')),
                ('vidmail', models.CharField(blank=True, choices=[('rab', 'E-mail рабочий КЛ'), ('dop', 'E-mail дополнительный КЛ'), ('lich', 'E-mail личный')], max_length=255, null=True, verbose_name='Вид почты')),
                ('meaning', models.CharField(blank=True, max_length=255, null=True)),
                ('ext', models.CharField(blank=True, max_length=255, null=True, verbose_name='Доб.')),
                ('comment', models.CharField(blank=True, max_length=255, null=True, verbose_name='Комментарий')),
                ('id', api.base_objects.UUIDPKField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Уникальный идентификатор')),
            ],
            options={
                'verbose_name': 'Контактная информация КА',
                'verbose_name_plural': 'Контактная информация КА',
                'db_table': 'counterparty_contact_info',
            },
        ),
        migrations.CreateModel(
            name='Counterparty',
            fields=[
                ('id', api.base_objects.UUIDPKField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Уникальный идентификатор')),
                ('is_active', models.BooleanField(default=True, verbose_name='Актуальность')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('code1c', models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='Код из 1С')),
                ('opf', models.CharField(blank=True, choices=[('IP', 'ИП'), ('FL', 'ФЛ'), ('SE', 'Самозанятый'), ('AO', 'АО'), ('BF', 'БФ'), ('ZAO', 'ЗАО'), ('MAU', 'МАУ'), ('MP', 'МП'), ('OAO', 'ОАО'), ('OOO', 'ООО'), ('PAO', 'ПАО'), ('TCN', 'ТСН')], max_length=64, null=True, verbose_name='ОПФ')),
                ('inn', models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='ИНН')),
                ('first_name', models.CharField(default='', max_length=64, verbose_name='Имя')),
                ('middle_name', models.CharField(blank=True, default='', max_length=64, verbose_name='Отчество')),
                ('last_name', models.CharField(default='', max_length=64, verbose_name='Фамилия')),
                ('description', models.CharField(blank=True, default='', max_length=256, null=True, verbose_name='Описание')),
                ('keyword', models.CharField(blank=True, default='', max_length=256, null=True, verbose_name='Ключевое слово')),
                ('additional_name', models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='Доп. название')),
                ('broadcast', models.BooleanField(default=False, verbose_name='Корпоративное вещание')),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counterparties', to='addresses.address')),
                ('brands', models.ManyToManyField(blank=True, related_name='counterparties', to='brands.brand', verbose_name='Бренды КА')),
            ],
            options={
                'verbose_name': 'Контрагент',
                'verbose_name_plural': 'Контрагенты',
                'db_table': 'counterparties',
                'ordering': ('-created',),
            },
            managers=[
                ('active', django.db.models.manager.Manager()),
            ],
        ),
    ]
