# Generated by Django 6.0.1 on 2026-03-30 10:39

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('counterparties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='counterparty',
            name='contact_persons',
            field=models.ManyToManyField(blank=True, related_name='counterparties', to=settings.AUTH_USER_MODEL, verbose_name='Контактное лицо'),
        ),
        migrations.AddField(
            model_name='counterparty',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='Создатель'),
        ),
        migrations.AddField(
            model_name='counterpartycontactinfo',
            name='counterparty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='counterparties.counterparty', verbose_name='Контрагент'),
        ),
        migrations.AddIndex(
            model_name='counterparty',
            index=django.contrib.postgres.indexes.GinIndex(fields=['first_name', 'middle_name', 'last_name'], name='counterparty_name_gin_idx', opclasses=['gin_trgm_ops', 'gin_trgm_ops', 'gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='counterparty',
            index=django.contrib.postgres.indexes.GinIndex(fields=['keyword'], name='counterparty_keyword_gin_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='counterparty',
            index=django.contrib.postgres.indexes.GinIndex(fields=['description'], name='counterparty_desc_gin_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='counterparty',
            index=models.Index(fields=['keyword'], name='counterpart_keyword_eddaa6_idx'),
        ),
        migrations.AddIndex(
            model_name='counterparty',
            index=models.Index(fields=['description'], name='counterpart_descrip_be780c_idx'),
        ),
        migrations.AddIndex(
            model_name='counterparty',
            index=models.Index(fields=['inn'], name='counterpart_inn_517b13_idx'),
        ),
        migrations.AddIndex(
            model_name='counterparty',
            index=models.Index(fields=['code1c'], name='counterpart_code1c_0ccb5e_idx'),
        ),
        migrations.AddIndex(
            model_name='counterparty',
            index=models.Index(fields=['address'], name='counterpart_address_281b0a_idx'),
        ),
        migrations.AddIndex(
            model_name='counterparty',
            index=models.Index(fields=['additional_name'], name='counterpart_additio_2e67d9_idx'),
        ),
    ]
