# Generated by Codex on 2026-08-12

import uuid

from django.db import migrations, models


def create_default_tenant_categories(apps, schema_editor):
    TenantCategory = apps.get_model('counterparties', 'TenantCategory')
    for name in (
        'Детские товары',
        'Электроника',
        'Банки и финансы',
        'Одежда и обувь',
        'Косметика',
    ):
        TenantCategory.objects.get_or_create(name=name)


class Migration(migrations.Migration):

    dependencies = [
        ('counterparties', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantCategory',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    'name',
                    models.CharField(
                        max_length=64,
                        unique=True,
                        verbose_name='Название',
                    ),
                ),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Категория арендатора',
                'verbose_name_plural': 'Категории арендаторов',
                'db_table': 'tenant_categories',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='TenantCategoryAssignment',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата назначения')),
                (
                    'category',
                    models.ForeignKey(
                        on_delete=models.deletion.CASCADE,
                        related_name='counterparty_assignments',
                        to='counterparties.tenantcategory',
                        verbose_name='Категория',
                    ),
                ),
                (
                    'counterparty',
                    models.ForeignKey(
                        on_delete=models.deletion.CASCADE,
                        related_name='category_assignments',
                        to='counterparties.counterparty',
                        verbose_name='Арендатор',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Назначение категории арендатору',
                'verbose_name_plural': 'Назначения категорий арендаторам',
                'db_table': 'tenant_category_assignments',
                'constraints': [
                    models.UniqueConstraint(
                        fields=('counterparty', 'category'),
                        name='unique_tenant_category_assignment',
                    ),
                ],
            },
        ),
        migrations.AddField(
            model_name='counterparty',
            name='categories',
            field=models.ManyToManyField(
                blank=True,
                related_name='counterparties',
                through='counterparties.TenantCategoryAssignment',
                through_fields=('counterparty', 'category'),
                to='counterparties.tenantcategory',
                verbose_name='Категории арендатора',
            ),
        ),
        migrations.RunPython(
            create_default_tenant_categories,
            migrations.RunPython.noop,
        ),
    ]
