# Generated by Codex on 2026-08-12

import uuid

from django.db import migrations, models
import django.db.models.functions.text


def create_default_counterparty_categories(apps, schema_editor):
    CounterpartyCategory = apps.get_model('counterparties', 'CounterpartyCategory')
    for name in (
        'Детские товары',
        'Электроника',
        'Банки и финансы',
        'Одежда и обувь',
        'Косметика',
    ):
        CounterpartyCategory.objects.get_or_create(name=name)


class Migration(migrations.Migration):

    dependencies = [
        ('counterparties', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CounterpartyCategory',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    'name',
                    models.CharField(
                        max_length=64,
                        unique=True,
                        verbose_name='Название',
                    ),
                ),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Категория контрагента',
                'verbose_name_plural': 'Категории контрагентов',
                'db_table': 'counterparty_categories',
                'ordering': ('name',),
                'indexes': [
                    models.Index(
                        django.db.models.functions.text.Upper('name'),
                        condition=models.Q(('is_active', True)),
                        name='counterparty_category_name_ci_idx',
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name='CounterpartyCategoryAssignment',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата назначения')),
                (
                    'category',
                    models.ForeignKey(
                        on_delete=models.deletion.CASCADE,
                        related_name='counterparty_assignments',
                        to='counterparties.counterpartycategory',
                        verbose_name='Категория',
                    ),
                ),
                (
                    'counterparty',
                    models.ForeignKey(
                        on_delete=models.deletion.CASCADE,
                        related_name='category_assignments',
                        to='counterparties.counterparty',
                        verbose_name='Контрагент',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Назначение категории контрагенту',
                'verbose_name_plural': 'Назначения категорий контрагентам',
                'db_table': 'counterparty_category_assignments',
                'constraints': [
                    models.UniqueConstraint(
                        fields=('counterparty', 'category'),
                        name='unique_counterparty_category_assignment',
                    ),
                ],
                'indexes': [
                    models.Index(
                        fields=('category', 'counterparty'),
                        name='counterparty_category_lookup_idx',
                    ),
                ],
            },
        ),
        migrations.AddField(
            model_name='counterparty',
            name='categories',
            field=models.ManyToManyField(
                blank=True,
                related_name='counterparties',
                through='counterparties.CounterpartyCategoryAssignment',
                through_fields=('counterparty', 'category'),
                to='counterparties.counterpartycategory',
                verbose_name='Категории контрагента',
            ),
        ),
        migrations.RunPython(
            create_default_counterparty_categories,
            migrations.RunPython.noop,
        ),
    ]
