# Generated by Django 6.0.1 on 2026-03-30 10:39

import django.contrib.postgres.indexes
import django_minio_backend.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ИД')),
                ('code1c', models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='Код из 1С')),
                ('name', models.CharField(max_length=64, verbose_name='Наименование бренда')),
                ('description', models.TextField(blank=True, default=None, max_length=255, null=True, verbose_name='Описание бренда')),
                ('logotype', models.FileField(blank=True, null=True, storage=django_minio_backend.models.MinioBackend(bucket_name='local-media'), upload_to='brand_logo', verbose_name='Логотип бренда')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Удалён')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления')),
            ],
            options={
                'verbose_name': 'Бренд',
                'verbose_name_plural': 'Бренды',
                'db_table': 'brands',
                'ordering': ('-created',),
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['name'], name='brand_name_gin_idx', opclasses=['gin_trgm_ops']), models.Index(fields=['name'], name='brands_name_c58671_idx'), models.Index(fields=['description'], name='brands_descrip_34841c_idx')],
            },
        ),
    ]
