# Generated by Django 6.0.1 on 2026-03-30 10:39

import api.base_objects
import api.custom_managers
import django.contrib.postgres.indexes
import django.core.validators
import django.db.models.deletion
import django_minio_backend.models
import phonenumber_field.modelfields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', api.base_objects.UUIDPKField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Уникальный идентификатор')),
                ('avatar', models.FileField(blank=True, null=True, storage=django_minio_backend.models.MinioBackend(bucket_name='local-media'), upload_to='user_avatars', verbose_name='Аватар пользователя')),
                ('last_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Фамилия')),
                ('first_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Имя')),
                ('middle_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Отчество')),
                ('role', models.CharField(choices=[('ordinary', 'Пользователь'), ('broadcast', 'Корп. вещание'), ('ad', 'Реклама'), ('admin', 'Сотрудник ТО'), ('manager', 'Менеджер'), ('superuser', 'Суперпользователь')], default='ordinary', max_length=32, verbose_name='Роль')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='RU', unique=True, verbose_name='Номер телефона')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, unique=True, validators=[django.core.validators.EmailValidator(message='Емэйл уже занят, либо введён некорректно. Разрешены только буквы, цифры и @/./+/-/_ символы, а почта должна иметь такой вид: адрес@домен')], verbose_name='Электронная почта')),
                ('is_active', models.BooleanField(default=True, verbose_name='Актуальность пользователя')),
                ('is_staff', models.BooleanField(default=False, help_text='Влияет на возможность зайти в админ-панель django', verbose_name='Пользователь админ-панели')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('code1c', models.CharField(blank=True, default='', null=True, verbose_name='Код 1с')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'db_table': 'custom_user',
                'ordering': ('-created',),
            },
            managers=[
                ('objects', api.custom_managers.CustomUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('basic', models.BooleanField(default=False, verbose_name='Основной')),
                ('type', models.CharField(blank=True, choices=[('address', 'Адрес'), ('phone', 'Телефон'), ('mail', 'Адрес электронной почты'), ('web', 'Веб-страница'), ('messenger', 'Мессенджер'), ('other', 'Другое')], max_length=255, null=True)),
                ('vidtel', models.CharField(blank=True, choices=[('mobkl', 'Телефон мобильный КЛ'), ('dop', 'Дополнительный'), ('mobkldop', 'Телефон дополнительный КЛ')], max_length=255, null=True, verbose_name='Вид телефона')),
                ('vidmail', models.CharField(blank=True, choices=[('rab', 'E-mail рабочий КЛ'), ('dop', 'E-mail дополнительный КЛ'), ('lich', 'E-mail личный')], max_length=255, null=True, verbose_name='Вид почты')),
                ('meaning', models.CharField(blank=True, max_length=255, null=True)),
                ('ext', models.CharField(blank=True, max_length=255, null=True, verbose_name='Доб.')),
                ('comment', models.CharField(blank=True, max_length=255, null=True, verbose_name='Комментарий')),
                ('id', api.base_objects.UUIDPKField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Уникальный идентификатор')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts_cp', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Контактная информация',
                'verbose_name_plural': 'Контактная информация',
                'db_table': 'contact_info',
            },
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=django.contrib.postgres.indexes.GinIndex(fields=['first_name', 'middle_name', 'last_name'], name='user_name_gin_idx', opclasses=['gin_trgm_ops', 'gin_trgm_ops', 'gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['email'], name='custom_user_email_55dec9_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['first_name'], name='custom_user_first_n_c3facc_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['last_name'], name='custom_user_last_na_ec1111_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['phone_number'], name='custom_user_phone_n_b19049_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['code1c'], name='custom_user_code1c_a9f255_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['role'], name='custom_user_role_aeef4e_idx'),
        ),
    ]
