# Generated by Django 6.0.1 on 2026-05-05 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='token_1c_access',
            field=models.TextField(blank=True, null=True, verbose_name='Access-токен 1С'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='token_1c_refresh',
            field=models.TextField(blank=True, null=True, verbose_name='Refresh-токен 1С'),
        ),
    ]
