# Generated by Django 5.0.3 on 2024-04-04 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('admin', 'Сотрудник ТО'), ('manager', 'Менеджер'), ('superuser', 'Суперпользователь')], max_length=32, null=True, verbose_name='Роль'),
        ),
    ]
