# Generated by Django 5.0.3 on 2024-03-29 08:55

import django.db.models.functions.text
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Уникальный идентификатор')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('md5hash', models.CharField(editable=False, max_length=32, verbose_name='MD5')),
                ('sha256hash', models.CharField(editable=False, max_length=256, verbose_name='SHA256')),
                ('hash', models.CharField(max_length=288, verbose_name=django.db.models.functions.text.Concat(models.CharField(editable=False, max_length=32, verbose_name='MD5'), models.CharField(editable=False, max_length=256, verbose_name='SHA256')))),
                ('length', models.TimeField(editable=False, verbose_name='Продолжительность')),
                ('size', models.IntegerField(editable=False, verbose_name='Размер')),
                ('file_type', models.PositiveSmallIntegerField(choices=[(0, 'Реклама'), (1, 'Музыка'), (2, 'Кртинка фон'), (3, 'Видео фон'), (4, 'Бегущая строка')], verbose_name='Тип')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='PlaylistFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PlaylistSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broadcast_type', models.PositiveSmallIntegerField(choices=[(0, 'По времени работы точки'), (1, 'Начало работы + смещение по времени'), (2, 'Конец работы - смещение по времени'), (3, 'Конкретные часы'), (4, 'С открытия до фиксированного часа'), (5, 'С фиксированного часа до закрытия'), (6, 'Старт по событию')], verbose_name='Тип вещания')),
                ('parameters', models.JSONField(verbose_name='Параметры заказа')),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, unique=True, verbose_name='Наименование')),
            ],
        ),
    ]
