# Generated by Django 6.0.1 on 2026-09-23 16:58

import api.base_objects
import colorfield.fields
import django.db.models.manager
import django_minio_backend.models
import files.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', api.base_objects.UUIDPKField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Уникальный идентификатор')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('is_active', models.BooleanField(default=True, verbose_name='Актуальность')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('source', models.FileField(storage=django_minio_backend.models.MinioBackend(bucket_name='local-media'), upload_to=files.models.media_path, verbose_name='Файл')),
                ('md5hash', models.CharField(editable=False, max_length=32, verbose_name='MD5')),
                ('sha256hash', models.CharField(editable=False, max_length=64, verbose_name='SHA256')),
                ('hash', models.CharField(editable=False, max_length=96, unique=True)),
                ('length', models.TimeField(blank=True, editable=False, null=True, verbose_name='Продолжительность')),
                ('size', models.IntegerField(default=0, editable=False, verbose_name='Размер')),
                ('type', models.PositiveSmallIntegerField(choices=[(0, 'music'), (1, 'video'), (2, 'image'), (3, 'ticker'), (4, 'ad')], verbose_name='Тип')),
                ('subtype', models.CharField(blank=True, choices=[('music_pop', 'Поп-музыка'), ('music_rock', 'Рок'), ('music_jazz', 'Джаз'), ('music_classical', 'Классика'), ('music_electronic', 'Электронная'), ('music_hiphop', 'Хип-хоп'), ('video_short', 'Короткое видео'), ('video_long', 'Длинное видео'), ('video_promo', 'Промо-ролик'), ('video_animation', 'Анимация'), ('image_photo', 'Фотография'), ('image_illustration', 'Иллюстрация'), ('image_logo', 'Логотип'), ('image_banner', 'Баннер'), ('image_background', 'Фон'), ('ticker_text', 'Текстовая строка'), ('ticker_animated', 'Анимированная строка'), ('ad_banner', 'Баннерная реклама'), ('ad_video', 'Видеореклама'), ('ad_audio', 'Аудиореклама')], help_text='Детальная классификация (только для админки)', max_length=50, null=True, verbose_name='Подтип')),
            ],
            options={
                'verbose_name': 'Файл',
                'verbose_name_plural': 'Файлы',
                'db_table': 'file',
                'ordering': ('-created',),
            },
            managers=[
                ('active', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', api.base_objects.UUIDPKField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Уникальный идентификатор')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('is_active', models.BooleanField(default=True, verbose_name='Актуальность')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Плейлист',
                'verbose_name_plural': 'Плейлисты',
                'db_table': 'playlist',
                'ordering': ('-created',),
            },
            managers=[
                ('active', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название')),
                ('color', colorfield.fields.ColorField(blank=True, default=None, image_field=None, max_length=25, null=True, samples=None, verbose_name='Цвет')),
            ],
            options={
                'verbose_name': 'Тэг',
                'verbose_name_plural': 'Тэги',
                'db_table': 'tag',
                'ordering': ('name',),
            },
        ),
    ]
