# Generated by Django 5.0.3 on 2024-04-01 03:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('files', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to=settings.AUTH_USER_MODEL, verbose_name='Кто загрузил'),
        ),
        migrations.AddField(
            model_name='playlistfiles',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file', to='files.file', verbose_name='Файл'),
        ),
        migrations.AddField(
            model_name='playlistfiles',
            name='images',
            field=models.ManyToManyField(related_name='slides', to='files.file', verbose_name='Слайд'),
        ),
        migrations.AddField(
            model_name='playlistfiles',
            name='playlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist', to='files.playlist', verbose_name='Плейлист'),
        ),
        migrations.AddField(
            model_name='playlist',
            name='files',
            field=models.ManyToManyField(related_name='playlist_files', through='files.PlaylistFiles', to='files.file', verbose_name='Файлы'),
        ),
        migrations.AddField(
            model_name='playlist',
            name='settings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist_settings', to='files.playlistsetting', verbose_name='Настройки'),
        ),
        migrations.AddField(
            model_name='file',
            name='theme',
            field=models.ManyToManyField(related_name='files', to='files.theme', verbose_name='Тематика'),
        ),
    ]
