# Generated by Django 5.0.3 on 2024-05-07 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlistfiles',
            name='images',
            field=models.ManyToManyField(blank=True, null=True, related_name='slides', to='files.file', verbose_name='Слайд'),
        ),
    ]
