# Generated by Django 5.0.3 on 2024-04-02 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='source',
            field=models.FileField(blank=True, null=True, upload_to='files/source/', verbose_name='Файл'),
        ),
    ]
