# Generated by Django 5.2.3 on 2025-06-27 00:10

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='color',
            field=colorfield.fields.ColorField(blank=True, default=None, image_field=None, max_length=25, null=True, samples=None, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='file',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'music'), (1, 'video'), (2, 'image'), (3, 'ticker'), (4, 'ad')], verbose_name='Тип'),
        ),
    ]
