# Generated by Django 5.0.3 on 2024-05-13 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_alter_playlistfiles_images'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Тематику', 'verbose_name_plural': 'Тематики'},
        ),
        migrations.AlterField(
            model_name='playlistfiles',
            name='images',
            field=models.ManyToManyField(related_name='slides', to='files.file', verbose_name='Слайд'),
        ),
    ]
