# Generated by Django 6.0.1 on 2026-05-07 12:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='subtype',
            field=models.CharField(blank=True, choices=[('music_pop', 'Поп-музыка'), ('music_rock', 'Рок'), ('music_jazz', 'Джаз'), ('music_classical', 'Классика'), ('music_electronic', 'Электронная'), ('music_hiphop', 'Хип-хоп'), ('video_short', 'Короткое видео'), ('video_long', 'Длинное видео'), ('video_promo', 'Промо-ролик'), ('video_animation', 'Анимация'), ('image_photo', 'Фотография'), ('image_illustration', 'Иллюстрация'), ('image_logo', 'Логотип'), ('image_banner', 'Баннер'), ('image_background', 'Фон'), ('ticker_text', 'Текстовая строка'), ('ticker_animated', 'Анимированная строка'), ('ad_banner', 'Баннерная реклама'), ('ad_video', 'Видеореклама'), ('ad_audio', 'Аудиореклама')], help_text='Детальная классификация файла (только для информации в админке)', max_length=50, null=True, verbose_name='Подтип'),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['hash'], name='file_hash_idx'),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['type'], name='file_type_idx'),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['subtype'], name='file_subtype_idx'),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['is_active'], name='file_active_idx'),
        ),
    ]
