# Generated by Django 5.0.3 on 2024-04-17 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_file_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='settings',
        ),
        migrations.AlterField(
            model_name='playlistfiles',
            name='images',
            field=models.ManyToManyField(related_name='slides', to='files.file', verbose_name='Слайды'),
        ),
        migrations.DeleteModel(
            name='PlaylistSetting',
        ),
    ]
