# Generated by Django 5.2.3 on 2025-07-01 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_tag_color_alter_file_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(editable=False, max_length=255, unique=True, verbose_name='Название'),
        ),
    ]
