# Generated by Django 6.0.1 on 2026-05-18 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_add_file_subtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='subtype',
            field=models.CharField(blank=True, choices=[('music_pop', 'Поп-музыка'), ('music_rock', 'Рок'), ('music_jazz', 'Джаз'), ('music_classical', 'Классика'), ('music_electronic', 'Электронная'), ('music_hiphop', 'Хип-хоп'), ('video_short', 'Короткое видео'), ('video_long', 'Длинное видео'), ('video_promo', 'Промо-ролик'), ('video_animation', 'Анимация'), ('image_photo', 'Фотография'), ('image_illustration', 'Иллюстрация'), ('image_logo', 'Логотип'), ('image_banner', 'Баннер'), ('image_background', 'Фон'), ('ticker_text', 'Текстовая строка'), ('ticker_animated', 'Анимированная строка'), ('ad_banner', 'Баннерная реклама'), ('ad_video', 'Видеореклама'), ('ad_audio', 'Аудиореклама')], help_text='Детальная классификация (только для админки)', max_length=50, null=True, verbose_name='Подтип'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Название'),
        ),
    ]
