# Generated by Django 5.0.3 on 2024-04-15 10:24

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_file_source'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaylistSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broadcast_type', models.PositiveSmallIntegerField(choices=[(0, 'По времени работы точки'), (1, 'Начало работы + смещение по времени'), (2, 'Конец работы - смещение по времени'), (3, 'Конкретные часы'), (4, 'С открытия до фиксированного часа'), (5, 'С фиксированного часа до закрытия'), (6, 'Старт по событию')], default=0, verbose_name='Тип вещания')),
                ('parameters', models.JSONField(verbose_name='Параметры заказа')),
            ],
            options={
                'verbose_name': 'Настройки',
                'verbose_name_plural': 'Настройки',
            },
        ),
        migrations.AlterModelOptions(
            name='file',
            options={'verbose_name': 'Файл', 'verbose_name_plural': 'Файлы'},
        ),
        migrations.AlterModelOptions(
            name='playlist',
            options={'verbose_name': 'Плейлист', 'verbose_name_plural': 'Плейлисты'},
        ),
        migrations.AlterModelOptions(
            name='playlistfiles',
            options={'verbose_name': 'Файл плейлиста', 'verbose_name_plural': 'Файлы плейлиста'},
        ),
        migrations.AlterModelOptions(
            name='theme',
            options={'verbose_name': 'Тематика', 'verbose_name_plural': 'Тематики'},
        ),
        migrations.AddField(
            model_name='playlist',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='playlists', to=settings.AUTH_USER_MODEL, verbose_name='Плейлисты'),
        ),
        migrations.AlterField(
            model_name='file',
            name='hash',
            field=models.CharField(editable=False, max_length=288, verbose_name=django.db.models.functions.text.Concat(models.CharField(editable=False, max_length=32, verbose_name='MD5'), models.CharField(editable=False, max_length=256, verbose_name='SHA256'))),
        ),
        migrations.AlterField(
            model_name='file',
            name='length',
            field=models.TimeField(default='00:00:00', editable=False, verbose_name='Продолжительность'),
        ),
        migrations.AlterField(
            model_name='file',
            name='size',
            field=models.IntegerField(default=0, editable=False, verbose_name='Размер'),
        ),
        migrations.AlterField(
            model_name='file',
            name='source',
            field=models.FileField(upload_to='files/source/', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='file',
            name='theme',
            field=models.ManyToManyField(blank=True, null=True, related_name='files', to='files.theme', verbose_name='Тематика'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='settings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist_settings', to='files.playlistsettings', verbose_name='Настройки'),
        ),
        migrations.DeleteModel(
            name='PlaylistSetting',
        ),
    ]
