# Generated by Django 5.0.3 on 2024-04-23 09:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0004_playlistsettings_alter_file_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Theme',
            new_name='Tag',
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='settings',
        ),
        migrations.RemoveField(
            model_name='file',
            name='theme',
        ),
        migrations.AddField(
            model_name='file',
            name='tag',
            field=models.ManyToManyField(related_name='files', to='files.tag', verbose_name='Тематика'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='playlists', to=settings.AUTH_USER_MODEL, verbose_name='Создатель'),
        ),
        migrations.DeleteModel(
            name='PlaylistSettings',
        ),
    ]
