# Generated by Django 6.0.1 on 2026-09-23 16:58

import api.base_objects
import django.contrib.postgres.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', api.base_objects.UUIDPKField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Уникальный идентификатор')),
                ('code1c', models.CharField(blank=True, null=True, verbose_name='Код 1с')),
                ('name', models.CharField(blank=True, null=True, verbose_name='Имя')),
                ('phone', models.CharField(blank=True, null=True, verbose_name='Телефон')),
                ('email', models.CharField(blank=True, null=True, verbose_name='Почта')),
                ('message', models.CharField(blank=True, null=True, verbose_name='Текст обращения')),
                ('pathname', models.CharField(blank=True, null=True, verbose_name='Раздел сайта')),
                ('brand_id', models.CharField(blank=True, null=True, verbose_name='ID бренда')),
                ('nomenclatures_ids', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), blank=True, null=True, verbose_name='ID номенклатур')),
                ('attribution', models.JSONField(blank=True, null=True, verbose_name='Marketing attribution')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Обратная связь',
                'verbose_name_plural': 'Обратные связи',
                'db_table': 'feedback',
                'ordering': ('-created',),
            },
        ),
    ]
