# Generated by Django 6.0.1 on 2026-09-23 16:58

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('feedback', '0001_initial'),
        ('placement_order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='placement_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_requests', to='placement_order.placementorder', verbose_name='Placement order'),
        ),
        migrations.AddIndex(
            model_name='feedback',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='feedback_name_gin_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='feedback',
            index=models.Index(fields=['name'], name='feedback_name_fc5b23_idx'),
        ),
        migrations.AddIndex(
            model_name='feedback',
            index=models.Index(fields=['code1c'], name='feedback_code1c_4d2c14_idx'),
        ),
    ]
