# Generated by Django 6.0.1 on 2026-04-28 10:30

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='feedback',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='feedback_name_gin_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='feedback',
            index=models.Index(fields=['name'], name='feedback_name_fc5b23_idx'),
        ),
        migrations.AddIndex(
            model_name='feedback',
            index=models.Index(fields=['code1c'], name='feedback_code1c_4d2c14_idx'),
        ),
    ]
