# Generated by Django 6.0.1 on 2026-05-18 11:02

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_feedback_feedback_name_gin_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='brand_id',
            field=models.CharField(blank=True, null=True, verbose_name='ID бренда'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='nomenclatures_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), blank=True, null=True, verbose_name='ID номенклатур'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='pathname',
            field=models.CharField(blank=True, null=True, verbose_name='Раздел сайта'),
        ),
    ]
